// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/high_impact_coverage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:origna_gta/core/repositories/order_repository.dart' as _i7;
import 'package:origna_gta/core/repositories/user_repository.dart' as _i2;
import 'package:origna_gta/features/admin/admin_actions_viewmodel.dart' as _i3;
import 'package:origna_gta/models/generated/models.dart' as _i8;
import 'package:origna_gta/utils/utils.dart' as _i5;
import 'package:state_notifier/state_notifier.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSellerAccountStatus_0 extends _i1.SmartFake
    implements _i2.SellerAccountStatus {
  _FakeSellerAccountStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminActionsState_1 extends _i1.SmartFake
    implements _i3.AdminActionsState {
  _FakeAdminActionsState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  @override
  _i4.Future<String> addBuyerAddress(_i5.Address? address) =>
      (super.noSuchMethod(
            Invocation.method(#addBuyerAddress, [address]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBuyerAddress, [addressId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.SellerAccountStatus> getSellerAccountStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getSellerAccountStatus, [userId]),
            returnValue: _i4.Future<_i2.SellerAccountStatus>.value(
              _FakeSellerAccountStatus_0(
                this,
                Invocation.method(#getSellerAccountStatus, [userId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.SellerAccountStatus>.value(
                  _FakeSellerAccountStatus_0(
                    this,
                    Invocation.method(#getSellerAccountStatus, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.SellerAccountStatus>);

  @override
  _i4.Future<_i5.UserModel?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i4.Future<_i5.UserModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.UserModel?>.value(),
          )
          as _i4.Future<_i5.UserModel?>);

  @override
  _i4.Future<void> recordTermsAcceptance() =>
      (super.noSuchMethod(
            Invocation.method(#recordTermsAcceptance, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setDefaultBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultBuyerAddress, [addressId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBuyerAddress(
    String? addressId,
    _i5.Address? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerAddress, [addressId, address]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateNotificationPreferences(
    String? userId, {
    bool? notifyNewProducts,
    bool? notifyTrending,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNotificationPreferences,
              [userId],
              {
                #notifyNewProducts: notifyNewProducts,
                #notifyTrending: notifyTrending,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePreferredLanguage(String? userId, String? lang) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferredLanguage, [userId, lang]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.Address>> watchAddresses(
    String? userId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchAddresses,
              [userId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Stream<List<_i5.Address>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i5.Address>>.empty(),
          )
          as _i4.Stream<List<_i5.Address>>);

  @override
  _i4.Stream<_i2.SellerAccountStatus> watchSellerAccountStatus(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerAccountStatus, [userId]),
            returnValue: _i4.Stream<_i2.SellerAccountStatus>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i2.SellerAccountStatus>.empty(),
          )
          as _i4.Stream<_i2.SellerAccountStatus>);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i7.OrderRepository {
  @override
  _i4.Future<void> cancelOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [orderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> approveShippingCost(String? orderId, bool? approved) =>
      (super.noSuchMethod(
            Invocation.method(#approveShippingCost, [orderId, approved]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> capturePayment(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#capturePayment, [orderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> confirmReceipt(String? orderId, {String? productId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmReceipt,
              [orderId],
              {#productId: productId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> createCheckoutSession(
    Map<String, dynamic>? orderData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCheckoutSession, [orderData]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i8.Order?> fetchOrderById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i4.Future<_i8.Order?>.value(),
            returnValueForMissingStub: _i4.Future<_i8.Order?>.value(),
          )
          as _i4.Future<_i8.Order?>);

  @override
  _i4.Future<void> updateItemStatus(
    String? orderId,
    String? itemId,
    String? status, {
    String? trackingNumber,
    String? carrier,
    String? carrierNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateItemStatus,
              [orderId, itemId, status],
              {
                #trackingNumber: trackingNumber,
                #carrier: carrier,
                #carrierNote: carrierNote,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateLastSession(
    String? userId,
    String? sessionId,
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSession, [userId, sessionId, orderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateShippingCost(
    String? orderId,
    int? newShippingCostCents,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShippingCost, [
              orderId,
              newShippingCostCents,
              reason,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i8.Order>> watchBuyerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBuyerOrders, [userId]),
            returnValue: _i4.Stream<List<_i8.Order>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i8.Order>>.empty(),
          )
          as _i4.Stream<List<_i8.Order>>);

  @override
  _i4.Stream<_i8.Order?> watchPaidOrderBySession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPaidOrderBySession, [sessionId]),
            returnValue: _i4.Stream<_i8.Order?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i8.Order?>.empty(),
          )
          as _i4.Stream<_i8.Order?>);

  @override
  _i4.Stream<List<_i8.Order>> watchSellerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerOrders, [userId]),
            returnValue: _i4.Stream<List<_i8.Order>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i8.Order>>.empty(),
          )
          as _i4.Stream<List<_i8.Order>>);

  @override
  _i4.Future<Map<String, dynamic>> createReturnRequest({
    required String? orderId,
    required List<String>? cartItemIds,
    required String? reason,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReturnRequest, [], {
              #orderId: orderId,
              #cartItemIds: cartItemIds,
              #reason: reason,
              #description: description,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i8.ReturnRequest>> fetchReturnRequests(
    String? orderId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchReturnRequests,
              [orderId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Future<List<_i8.ReturnRequest>>.value(
              <_i8.ReturnRequest>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i8.ReturnRequest>>.value(
                  <_i8.ReturnRequest>[],
                ),
          )
          as _i4.Future<List<_i8.ReturnRequest>>);
}

/// A class which mocks [AdminActionsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminActionsViewModel extends _i1.Mock
    implements _i3.AdminActionsViewModel {
  @override
  bool get mounted =>
      (super.noSuchMethod(
            Invocation.getter(#mounted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Stream<_i3.AdminActionsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i3.AdminActionsState>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i3.AdminActionsState>.empty(),
          )
          as _i4.Stream<_i3.AdminActionsState>);

  @override
  _i3.AdminActionsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAdminActionsState_1(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeAdminActionsState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AdminActionsState);

  @override
  _i3.AdminActionsState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeAdminActionsState_1(
              this,
              Invocation.getter(#debugState),
            ),
            returnValueForMissingStub: _FakeAdminActionsState_1(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i3.AdminActionsState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set onError(_i9.ErrorListener? value) => super.noSuchMethod(
    Invocation.setter(#onError, value),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i3.AdminActionsState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> approveProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#approveProduct, [productId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> rejectProduct(String? productId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#rejectProduct, [productId, reason]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> disableAdminMfa(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#disableAdminMfa, [code]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> enableAdminMfa() =>
      (super.noSuchMethod(
            Invocation.method(#enableAdminMfa, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<_i5.UserModel?> fetchUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserById, [userId]),
            returnValue: _i4.Future<_i5.UserModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.UserModel?>.value(),
          )
          as _i4.Future<_i5.UserModel?>);

  @override
  _i4.Future<bool> setUserSuspended(String? userId, bool? suspended) =>
      (super.noSuchMethod(
            Invocation.method(#setUserSuspended, [userId, suspended]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateProductStock(String? productId, int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductStock, [productId, quantity]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateUserRoles(
    String? userId, {
    List<String>? add = const [],
    List<String>? remove = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserRoles,
              [userId],
              {#add: add, #remove: remove},
            ),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> verifyAdminMfa(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAdminMfa, [code]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  bool updateShouldNotify(
    _i3.AdminActionsState? old,
    _i3.AdminActionsState? current,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.RemoveListener addListener(
    _i10.Listener<_i3.AdminActionsState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i9.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
