// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/widget/origna_app_routes_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:cross_file/cross_file.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:origna_gta/core/repositories/product_repository.dart' as _i3;
import 'package:origna_gta/core/schema/schema_constants.dart' as _i8;
import 'package:origna_gta/models/generated/models.dart' as _i5;
import 'package:origna_gta/services/push_transport.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppNotificationSettings_0 extends _i1.SmartFake
    implements _i2.AppNotificationSettings {
  _FakeAppNotificationSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductQueryResult_1 extends _i1.SmartFake
    implements _i3.ProductQueryResult {
  _FakeProductQueryResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PushMessagingClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushMessagingClient extends _i1.Mock
    implements _i2.PushMessagingClient {
  @override
  _i4.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(
            Invocation.getter(#onTokenRefresh),
            returnValue: _i4.Stream<String>.empty(),
            returnValueForMissingStub: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  _i4.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i2.AppRemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessage, []),
            returnValue: _i4.Future<_i2.AppRemoteMessage?>.value(),
            returnValueForMissingStub:
                _i4.Future<_i2.AppRemoteMessage?>.value(),
          )
          as _i4.Future<_i2.AppRemoteMessage?>);

  @override
  _i4.Future<_i2.AppNotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, [], {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
            }),
            returnValue: _i4.Future<_i2.AppNotificationSettings>.value(
              _FakeAppNotificationSettings_0(
                this,
                Invocation.method(#requestPermission, [], {
                  #alert: alert,
                  #announcement: announcement,
                  #badge: badge,
                  #carPlay: carPlay,
                  #criticalAlert: criticalAlert,
                  #provisional: provisional,
                  #sound: sound,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.AppNotificationSettings>.value(
                  _FakeAppNotificationSettings_0(
                    this,
                    Invocation.method(#requestPermission, [], {
                      #alert: alert,
                      #announcement: announcement,
                      #badge: badge,
                      #carPlay: carPlay,
                      #criticalAlert: criticalAlert,
                      #provisional: provisional,
                      #sound: sound,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.AppNotificationSettings>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i3.ProductRepository {
  @override
  _i4.Future<String> createProductAtomic(
    _i5.Product? product,
    List<_i6.Uint8List>? imageBytes, {
    List<String>? testImageUrls,
    String? bookSourceUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createProductAtomic,
              [product, imageBytes],
              {#testImageUrls: testImageUrls, #bookSourceUrl: bookSourceUrl},
            ),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #createProductAtomic,
                  [product, imageBytes],
                  {
                    #testImageUrls: testImageUrls,
                    #bookSourceUrl: bookSourceUrl,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #createProductAtomic,
                  [product, imageBytes],
                  {
                    #testImageUrls: testImageUrls,
                    #bookSourceUrl: bookSourceUrl,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Product?> fetchProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductById, [productId]),
            returnValue: _i4.Future<_i5.Product?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Product?>.value(),
          )
          as _i4.Future<_i5.Product?>);

  @override
  _i4.Future<_i3.ProductQueryResult> fetchProducts({
    String? searchQuery,
    int? categoryId,
    String? subcategory,
    String? lastDocumentId,
    int? pageSize = 20,
    _i8.SortOption? sortOption = _i8.SortOption.relevance,
    int? minPriceCents,
    int? maxPriceCents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {
              #searchQuery: searchQuery,
              #categoryId: categoryId,
              #subcategory: subcategory,
              #lastDocumentId: lastDocumentId,
              #pageSize: pageSize,
              #sortOption: sortOption,
              #minPriceCents: minPriceCents,
              #maxPriceCents: maxPriceCents,
            }),
            returnValue: _i4.Future<_i3.ProductQueryResult>.value(
              _FakeProductQueryResult_1(
                this,
                Invocation.method(#fetchProducts, [], {
                  #searchQuery: searchQuery,
                  #categoryId: categoryId,
                  #subcategory: subcategory,
                  #lastDocumentId: lastDocumentId,
                  #pageSize: pageSize,
                  #sortOption: sortOption,
                  #minPriceCents: minPriceCents,
                  #maxPriceCents: maxPriceCents,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.ProductQueryResult>.value(
              _FakeProductQueryResult_1(
                this,
                Invocation.method(#fetchProducts, [], {
                  #searchQuery: searchQuery,
                  #categoryId: categoryId,
                  #subcategory: subcategory,
                  #lastDocumentId: lastDocumentId,
                  #pageSize: pageSize,
                  #sortOption: sortOption,
                  #minPriceCents: minPriceCents,
                  #maxPriceCents: maxPriceCents,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.ProductQueryResult>);

  @override
  _i4.Future<List<_i5.Product>> fetchProductsByIds(List<String>? productIds) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductsByIds, [productIds]),
            returnValue: _i4.Future<List<_i5.Product>>.value(<_i5.Product>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Product>>.value(
              <_i5.Product>[],
            ),
          )
          as _i4.Future<List<_i5.Product>>);

  @override
  String generateProductId() =>
      (super.noSuchMethod(
            Invocation.method(#generateProductId, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateProductId, []),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateProductId, []),
            ),
          )
          as String);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAutocompleteSuggestions(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAutocompleteSuggestions, [query]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<_i5.Product?> getProductBySlug(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBySlug, [slug]),
            returnValue: _i4.Future<_i5.Product?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Product?>.value(),
          )
          as _i4.Future<_i5.Product?>);

  @override
  _i4.Future<String?> getUploadUrl(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadUrl, [fileName]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, String>?> getUploadUrlInfo(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadUrlInfo, [fileName]),
            returnValue: _i4.Future<Map<String, String>?>.value(),
            returnValueForMissingStub: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<Map<String, String>?> getUploadVideoUrlInfo(
    String? fileName,
    String? contentType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadVideoUrlInfo, [fileName, contentType]),
            returnValue: _i4.Future<Map<String, String>?>.value(),
            returnValueForMissingStub: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<void> submitRating(
    String? orderId,
    String? productId,
    int? rating, {
    List<String>? reviewImageUrls,
    String? reviewText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitRating,
              [orderId, productId, rating],
              {#reviewImageUrls: reviewImageUrls, #reviewText: reviewText},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> submitRatingAtomic(
    String? orderId,
    String? productId,
    int? rating, {
    List<_i6.Uint8List>? reviewImages,
    String? reviewText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitRatingAtomic,
              [orderId, productId, rating],
              {#reviewImages: reviewImages, #reviewText: reviewText},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleFavorite(String? userId, String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [userId, productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateProduct(
    String? productId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [productId, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> uploadImages(
    List<_i6.Uint8List>? images,
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImages, [images, productId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<String?> uploadProductVideo(
    _i9.XFile? videoFile,
    String? sellerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProductVideo, [videoFile, sellerId]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<List<String>> uploadReviewImages(
    List<_i6.Uint8List>? images,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadReviewImages, [images, userId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Stream<Set<String>> watchFavorites(
    String? userId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchFavorites,
              [userId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Stream<Set<String>>.empty(),
            returnValueForMissingStub: _i4.Stream<Set<String>>.empty(),
          )
          as _i4.Stream<Set<String>>);

  @override
  _i4.Stream<int> watchUnansweredQuestionsCount(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUnansweredQuestionsCount, [sellerId]),
            returnValue: _i4.Stream<int>.empty(),
            returnValueForMissingStub: _i4.Stream<int>.empty(),
          )
          as _i4.Stream<int>);
}
