// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/widget/product_details_screen_coverage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:origna_gta/features/cart/cart_provider.dart' as _i3;
import 'package:origna_gta/features/products/stock_notification_provider.dart'
    as _i5;
import 'package:state_notifier/state_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAsyncValue_0<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CartController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartController extends _i1.Mock implements _i3.CartController {
  @override
  _i4.Future<bool> addToCart(
    String? productId,
    int? quantity, {
    String? variantId,
    String? productName,
    double? priceCad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addToCart,
              [productId, quantity],
              {
                #variantId: variantId,
                #productName: productName,
                #priceCad: priceCad,
              },
            ),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> canAddToCart(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#canAddToCart, [productId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void refreshCart() => super.noSuchMethod(
    Invocation.method(#refreshCart, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> removeFromCart(String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [cartItemId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> saveForLater(String? productId, String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#saveForLater, [productId, cartItemId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateBuyerNote(String? cartItemId, String? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerNote, [cartItemId, note]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> updateQuantity(String? cartItemId, int? newQuantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [cartItemId, newQuantity]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [StockNotificationNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockStockNotificationNotifier extends _i1.Mock
    implements _i5.StockNotificationNotifier {
  @override
  String get productId =>
      (super.noSuchMethod(
            Invocation.getter(#productId),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#productId),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#productId),
            ),
          )
          as String);

  @override
  bool get mounted =>
      (super.noSuchMethod(
            Invocation.getter(#mounted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Stream<_i2.AsyncValue<bool>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.AsyncValue<bool>>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.AsyncValue<bool>>.empty(),
          )
          as _i4.Stream<_i2.AsyncValue<bool>>);

  @override
  _i2.AsyncValue<bool> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAsyncValue_0<bool>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeAsyncValue_0<bool>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.AsyncValue<bool>);

  @override
  _i2.AsyncValue<bool> get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeAsyncValue_0<bool>(
              this,
              Invocation.getter(#debugState),
            ),
            returnValueForMissingStub: _FakeAsyncValue_0<bool>(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i2.AsyncValue<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set onError(_i2.ErrorListener? value) => super.noSuchMethod(
    Invocation.setter(#onError, value),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i2.AsyncValue<bool>? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> subscribe() =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unsubscribe() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<bool>? old,
    _i2.AsyncValue<bool>? current,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.RemoveListener addListener(
    _i7.Listener<_i2.AsyncValue<bool>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i2.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
