// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/widget/product_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i7;

import 'package:cross_file/cross_file.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:origna_gta/core/repositories/product_repository.dart' as _i2;
import 'package:origna_gta/core/schema/schema_constants.dart' as _i9;
import 'package:origna_gta/features/cart/cart_provider.dart' as _i3;
import 'package:origna_gta/features/products/products_provider.dart' as _i5;
import 'package:origna_gta/models/generated/models.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductQueryResult_0 extends _i1.SmartFake
    implements _i2.ProductQueryResult {
  _FakeProductQueryResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CartController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartController extends _i1.Mock implements _i3.CartController {
  @override
  _i4.Future<bool> addToCart(
    String? productId,
    int? quantity, {
    String? variantId,
    String? productName,
    double? priceCad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addToCart,
              [productId, quantity],
              {
                #variantId: variantId,
                #productName: productName,
                #priceCad: priceCad,
              },
            ),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> canAddToCart(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#canAddToCart, [productId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void refreshCart() => super.noSuchMethod(
    Invocation.method(#refreshCart, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> removeFromCart(String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [cartItemId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> saveForLater(String? productId, String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#saveForLater, [productId, cartItemId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateBuyerNote(String? cartItemId, String? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerNote, [cartItemId, note]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> updateQuantity(String? cartItemId, int? newQuantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [cartItemId, newQuantity]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [FavoritesController].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesController extends _i1.Mock
    implements _i5.FavoritesController {
  @override
  bool isFavorite(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [productId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> toggleFavorite(
    String? productId, {
    String? productName,
    double? priceCad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #toggleFavorite,
              [productId],
              {#productName: productName, #priceCad: priceCad},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  @override
  _i4.Future<String> createProductAtomic(
    _i6.Product? product,
    List<_i7.Uint8List>? imageBytes, {
    List<String>? testImageUrls,
    String? bookSourceUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createProductAtomic,
              [product, imageBytes],
              {#testImageUrls: testImageUrls, #bookSourceUrl: bookSourceUrl},
            ),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #createProductAtomic,
                  [product, imageBytes],
                  {
                    #testImageUrls: testImageUrls,
                    #bookSourceUrl: bookSourceUrl,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #createProductAtomic,
                  [product, imageBytes],
                  {
                    #testImageUrls: testImageUrls,
                    #bookSourceUrl: bookSourceUrl,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.Product?> fetchProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductById, [productId]),
            returnValue: _i4.Future<_i6.Product?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.Product?>.value(),
          )
          as _i4.Future<_i6.Product?>);

  @override
  _i4.Future<_i2.ProductQueryResult> fetchProducts({
    String? searchQuery,
    int? categoryId,
    String? subcategory,
    String? lastDocumentId,
    int? pageSize = 20,
    _i9.SortOption? sortOption = _i9.SortOption.relevance,
    int? minPriceCents,
    int? maxPriceCents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {
              #searchQuery: searchQuery,
              #categoryId: categoryId,
              #subcategory: subcategory,
              #lastDocumentId: lastDocumentId,
              #pageSize: pageSize,
              #sortOption: sortOption,
              #minPriceCents: minPriceCents,
              #maxPriceCents: maxPriceCents,
            }),
            returnValue: _i4.Future<_i2.ProductQueryResult>.value(
              _FakeProductQueryResult_0(
                this,
                Invocation.method(#fetchProducts, [], {
                  #searchQuery: searchQuery,
                  #categoryId: categoryId,
                  #subcategory: subcategory,
                  #lastDocumentId: lastDocumentId,
                  #pageSize: pageSize,
                  #sortOption: sortOption,
                  #minPriceCents: minPriceCents,
                  #maxPriceCents: maxPriceCents,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ProductQueryResult>.value(
              _FakeProductQueryResult_0(
                this,
                Invocation.method(#fetchProducts, [], {
                  #searchQuery: searchQuery,
                  #categoryId: categoryId,
                  #subcategory: subcategory,
                  #lastDocumentId: lastDocumentId,
                  #pageSize: pageSize,
                  #sortOption: sortOption,
                  #minPriceCents: minPriceCents,
                  #maxPriceCents: maxPriceCents,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ProductQueryResult>);

  @override
  _i4.Future<List<_i6.Product>> fetchProductsByIds(List<String>? productIds) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductsByIds, [productIds]),
            returnValue: _i4.Future<List<_i6.Product>>.value(<_i6.Product>[]),
            returnValueForMissingStub: _i4.Future<List<_i6.Product>>.value(
              <_i6.Product>[],
            ),
          )
          as _i4.Future<List<_i6.Product>>);

  @override
  String generateProductId() =>
      (super.noSuchMethod(
            Invocation.method(#generateProductId, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#generateProductId, []),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#generateProductId, []),
            ),
          )
          as String);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAutocompleteSuggestions(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAutocompleteSuggestions, [query]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<_i6.Product?> getProductBySlug(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBySlug, [slug]),
            returnValue: _i4.Future<_i6.Product?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.Product?>.value(),
          )
          as _i4.Future<_i6.Product?>);

  @override
  _i4.Future<String?> getUploadUrl(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadUrl, [fileName]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, String>?> getUploadUrlInfo(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadUrlInfo, [fileName]),
            returnValue: _i4.Future<Map<String, String>?>.value(),
            returnValueForMissingStub: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<Map<String, String>?> getUploadVideoUrlInfo(
    String? fileName,
    String? contentType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadVideoUrlInfo, [fileName, contentType]),
            returnValue: _i4.Future<Map<String, String>?>.value(),
            returnValueForMissingStub: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<void> submitRating(
    String? orderId,
    String? productId,
    int? rating, {
    List<String>? reviewImageUrls,
    String? reviewText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitRating,
              [orderId, productId, rating],
              {#reviewImageUrls: reviewImageUrls, #reviewText: reviewText},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> submitRatingAtomic(
    String? orderId,
    String? productId,
    int? rating, {
    List<_i7.Uint8List>? reviewImages,
    String? reviewText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitRatingAtomic,
              [orderId, productId, rating],
              {#reviewImages: reviewImages, #reviewText: reviewText},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleFavorite(String? userId, String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [userId, productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateProduct(
    String? productId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [productId, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> uploadImages(
    List<_i7.Uint8List>? images,
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImages, [images, productId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<String?> uploadProductVideo(
    _i10.XFile? videoFile,
    String? sellerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProductVideo, [videoFile, sellerId]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<List<String>> uploadReviewImages(
    List<_i7.Uint8List>? images,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadReviewImages, [images, userId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Stream<Set<String>> watchFavorites(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchFavorites, [userId]),
            returnValue: _i4.Stream<Set<String>>.empty(),
            returnValueForMissingStub: _i4.Stream<Set<String>>.empty(),
          )
          as _i4.Stream<Set<String>>);

  @override
  _i4.Stream<int> watchUnansweredQuestionsCount(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUnansweredQuestionsCount, [sellerId]),
            returnValue: _i4.Stream<int>.empty(),
            returnValueForMissingStub: _i4.Stream<int>.empty(),
          )
          as _i4.Stream<int>);
}
