// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/screens/remaining_screens_batch7_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:cross_file/cross_file.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:origna_gta/core/repositories/order_repository.dart' as _i10;
import 'package:origna_gta/core/repositories/product_repository.dart' as _i2;
import 'package:origna_gta/core/repositories/user_repository.dart' as _i3;
import 'package:origna_gta/core/schema/schema_constants.dart' as _i8;
import 'package:origna_gta/models/generated/models.dart' as _i5;
import 'package:origna_gta/utils/utils.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductQueryResult_0 extends _i1.SmartFake
    implements _i2.ProductQueryResult {
  _FakeProductQueryResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSellerAccountStatus_1 extends _i1.SmartFake
    implements _i3.SellerAccountStatus {
  _FakeSellerAccountStatus_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  @override
  _i4.Future<String> createProductAtomic(
    _i5.Product? product,
    List<_i6.Uint8List>? imageBytes, {
    List<String>? testImageUrls,
    String? bookSourceUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createProductAtomic,
              [product, imageBytes],
              {#testImageUrls: testImageUrls, #bookSourceUrl: bookSourceUrl},
            ),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #createProductAtomic,
                  [product, imageBytes],
                  {
                    #testImageUrls: testImageUrls,
                    #bookSourceUrl: bookSourceUrl,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #createProductAtomic,
                  [product, imageBytes],
                  {
                    #testImageUrls: testImageUrls,
                    #bookSourceUrl: bookSourceUrl,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Product?> fetchProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductById, [productId]),
            returnValue: _i4.Future<_i5.Product?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Product?>.value(),
          )
          as _i4.Future<_i5.Product?>);

  @override
  _i4.Future<_i2.ProductQueryResult> fetchProducts({
    String? searchQuery,
    int? categoryId,
    String? subcategory,
    String? sellerId,
    String? lastDocumentId,
    int? pageSize = 20,
    _i8.SortOption? sortOption = _i8.SortOption.relevance,
    int? minPriceCents,
    int? maxPriceCents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {
              #searchQuery: searchQuery,
              #categoryId: categoryId,
              #subcategory: subcategory,
              #sellerId: sellerId,
              #lastDocumentId: lastDocumentId,
              #pageSize: pageSize,
              #sortOption: sortOption,
              #minPriceCents: minPriceCents,
              #maxPriceCents: maxPriceCents,
            }),
            returnValue: _i4.Future<_i2.ProductQueryResult>.value(
              _FakeProductQueryResult_0(
                this,
                Invocation.method(#fetchProducts, [], {
                  #searchQuery: searchQuery,
                  #categoryId: categoryId,
                  #subcategory: subcategory,
                  #sellerId: sellerId,
                  #lastDocumentId: lastDocumentId,
                  #pageSize: pageSize,
                  #sortOption: sortOption,
                  #minPriceCents: minPriceCents,
                  #maxPriceCents: maxPriceCents,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ProductQueryResult>.value(
              _FakeProductQueryResult_0(
                this,
                Invocation.method(#fetchProducts, [], {
                  #searchQuery: searchQuery,
                  #categoryId: categoryId,
                  #subcategory: subcategory,
                  #sellerId: sellerId,
                  #lastDocumentId: lastDocumentId,
                  #pageSize: pageSize,
                  #sortOption: sortOption,
                  #minPriceCents: minPriceCents,
                  #maxPriceCents: maxPriceCents,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ProductQueryResult>);

  @override
  _i4.Future<List<_i5.Product>> fetchProductsByIds(List<String>? productIds) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductsByIds, [productIds]),
            returnValue: _i4.Future<List<_i5.Product>>.value(<_i5.Product>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Product>>.value(
              <_i5.Product>[],
            ),
          )
          as _i4.Future<List<_i5.Product>>);

  @override
  String generateProductId() =>
      (super.noSuchMethod(
            Invocation.method(#generateProductId, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateProductId, []),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateProductId, []),
            ),
          )
          as String);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAutocompleteSuggestions(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAutocompleteSuggestions, [query]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<_i5.Product?> getProductBySlug(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBySlug, [slug]),
            returnValue: _i4.Future<_i5.Product?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Product?>.value(),
          )
          as _i4.Future<_i5.Product?>);

  @override
  _i4.Future<String?> getUploadUrl(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadUrl, [fileName]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, String>?> getUploadUrlInfo(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadUrlInfo, [fileName]),
            returnValue: _i4.Future<Map<String, String>?>.value(),
            returnValueForMissingStub: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<Map<String, String>?> getUploadVideoUrlInfo(
    String? fileName,
    String? contentType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadVideoUrlInfo, [fileName, contentType]),
            returnValue: _i4.Future<Map<String, String>?>.value(),
            returnValueForMissingStub: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<void> submitRating(
    String? orderId,
    String? productId,
    int? rating, {
    List<String>? reviewImageUrls,
    String? reviewText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitRating,
              [orderId, productId, rating],
              {#reviewImageUrls: reviewImageUrls, #reviewText: reviewText},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> submitRatingAtomic(
    String? orderId,
    String? productId,
    int? rating, {
    List<_i6.Uint8List>? reviewImages,
    String? reviewText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitRatingAtomic,
              [orderId, productId, rating],
              {#reviewImages: reviewImages, #reviewText: reviewText},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleFavorite(String? userId, String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [userId, productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateProduct(
    String? productId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [productId, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> uploadImages(
    List<_i6.Uint8List>? images,
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImages, [images, productId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<String?> uploadProductVideo(
    _i9.XFile? videoFile,
    String? sellerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProductVideo, [videoFile, sellerId]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<List<String>> uploadReviewImages(
    List<_i6.Uint8List>? images,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadReviewImages, [images, userId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Stream<Set<String>> watchFavorites(
    String? userId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchFavorites,
              [userId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Stream<Set<String>>.empty(),
            returnValueForMissingStub: _i4.Stream<Set<String>>.empty(),
          )
          as _i4.Stream<Set<String>>);

  @override
  _i4.Stream<int> watchUnansweredQuestionsCount(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUnansweredQuestionsCount, [sellerId]),
            returnValue: _i4.Stream<int>.empty(),
            returnValueForMissingStub: _i4.Stream<int>.empty(),
          )
          as _i4.Stream<int>);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i10.OrderRepository {
  @override
  _i4.Future<void> cancelOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [orderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> approveShippingCost(String? orderId, bool? approved) =>
      (super.noSuchMethod(
            Invocation.method(#approveShippingCost, [orderId, approved]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> capturePayment(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#capturePayment, [orderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> confirmReceipt(String? orderId, {String? productId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmReceipt,
              [orderId],
              {#productId: productId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> createCheckoutSession(
    Map<String, dynamic>? orderData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCheckoutSession, [orderData]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i5.Order?> fetchOrderById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i4.Future<_i5.Order?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Order?>.value(),
          )
          as _i4.Future<_i5.Order?>);

  @override
  _i4.Future<void> updateItemStatus(
    String? orderId,
    String? itemId,
    String? status, {
    String? trackingNumber,
    String? carrier,
    String? carrierNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateItemStatus,
              [orderId, itemId, status],
              {
                #trackingNumber: trackingNumber,
                #carrier: carrier,
                #carrierNote: carrierNote,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateLastSession(
    String? userId,
    String? sessionId,
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSession, [userId, sessionId, orderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateShippingCost(
    String? orderId,
    int? newShippingCostCents,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShippingCost, [
              orderId,
              newShippingCostCents,
              reason,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.Order>> watchBuyerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBuyerOrders, [userId]),
            returnValue: _i4.Stream<List<_i5.Order>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i5.Order>>.empty(),
          )
          as _i4.Stream<List<_i5.Order>>);

  @override
  _i4.Stream<_i5.Order?> watchPaidOrderBySession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPaidOrderBySession, [sessionId]),
            returnValue: _i4.Stream<_i5.Order?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i5.Order?>.empty(),
          )
          as _i4.Stream<_i5.Order?>);

  @override
  _i4.Stream<List<_i5.Order>> watchSellerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerOrders, [userId]),
            returnValue: _i4.Stream<List<_i5.Order>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i5.Order>>.empty(),
          )
          as _i4.Stream<List<_i5.Order>>);

  @override
  _i4.Future<Map<String, dynamic>> createReturnRequest({
    required String? orderId,
    required List<String>? cartItemIds,
    required String? reason,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReturnRequest, [], {
              #orderId: orderId,
              #cartItemIds: cartItemIds,
              #reason: reason,
              #description: description,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i5.ReturnRequest>> fetchReturnRequests(
    String? orderId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchReturnRequests,
              [orderId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Future<List<_i5.ReturnRequest>>.value(
              <_i5.ReturnRequest>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.ReturnRequest>>.value(
                  <_i5.ReturnRequest>[],
                ),
          )
          as _i4.Future<List<_i5.ReturnRequest>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  @override
  _i4.Future<String> addBuyerAddress(_i11.Address? address) =>
      (super.noSuchMethod(
            Invocation.method(#addBuyerAddress, [address]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBuyerAddress, [addressId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.SellerAccountStatus> getSellerAccountStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getSellerAccountStatus, [userId]),
            returnValue: _i4.Future<_i3.SellerAccountStatus>.value(
              _FakeSellerAccountStatus_1(
                this,
                Invocation.method(#getSellerAccountStatus, [userId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i3.SellerAccountStatus>.value(
                  _FakeSellerAccountStatus_1(
                    this,
                    Invocation.method(#getSellerAccountStatus, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i3.SellerAccountStatus>);

  @override
  _i4.Future<_i11.UserModel?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i4.Future<_i11.UserModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i11.UserModel?>.value(),
          )
          as _i4.Future<_i11.UserModel?>);

  @override
  _i4.Future<void> recordTermsAcceptance() =>
      (super.noSuchMethod(
            Invocation.method(#recordTermsAcceptance, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setDefaultBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultBuyerAddress, [addressId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBuyerAddress(
    String? addressId,
    _i11.Address? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerAddress, [addressId, address]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateNotificationPreferences(
    String? userId, {
    bool? notifyNewProducts,
    bool? notifyTrending,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNotificationPreferences,
              [userId],
              {
                #notifyNewProducts: notifyNewProducts,
                #notifyTrending: notifyTrending,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePreferredLanguage(String? userId, String? lang) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferredLanguage, [userId, lang]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i11.Address>> watchAddresses(
    String? userId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchAddresses,
              [userId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Stream<List<_i11.Address>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i11.Address>>.empty(),
          )
          as _i4.Stream<List<_i11.Address>>);

  @override
  _i4.Stream<_i3.SellerAccountStatus> watchSellerAccountStatus(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerAccountStatus, [userId]),
            returnValue: _i4.Stream<_i3.SellerAccountStatus>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i3.SellerAccountStatus>.empty(),
          )
          as _i4.Stream<_i3.SellerAccountStatus>);
}
