// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/unit/checkout_coverage_boost_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;

import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;
import 'package:origna_gta/core/repositories/order_repository.dart' as _i16;
import 'package:origna_gta/core/repositories/user_repository.dart' as _i2;
import 'package:origna_gta/models/generated/models.dart' as _i18;
import 'package:origna_gta/utils/utils.dart' as _i19;
import 'package:orignabase/src/auth.dart' as _i4;
import 'package:orignabase/src/batch.dart' as _i15;
import 'package:orignabase/src/client.dart' as _i21;
import 'package:orignabase/src/collection.dart' as _i14;
import 'package:orignabase/src/config.dart' as _i7;
import 'package:orignabase/src/links.dart' as _i9;
import 'package:orignabase/src/metrics.dart' as _i11;
import 'package:orignabase/src/offline.dart' as _i6;
import 'package:orignabase/src/presence.dart' as _i8;
import 'package:orignabase/src/push.dart' as _i10;
import 'package:orignabase/src/realtime.dart' as _i13;
import 'package:orignabase/src/storage.dart' as _i5;
import 'package:orignabase/src/vector.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSellerAccountStatus_0 extends _i1.SmartFake
    implements _i2.SellerAccountStatus {
  _FakeSellerAccountStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseAuth_2 extends _i1.SmartFake
    implements _i4.OrignaBaseAuth {
  _FakeOrignaBaseAuth_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseStorage_3 extends _i1.SmartFake
    implements _i5.OrignaBaseStorage {
  _FakeOrignaBaseStorage_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfflineCache_4 extends _i1.SmartFake implements _i6.OfflineCache {
  _FakeOfflineCache_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseConfig_5 extends _i1.SmartFake
    implements _i7.OrignaBaseConfig {
  _FakeOrignaBaseConfig_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePresence_6 extends _i1.SmartFake
    implements _i8.OrignaBasePresence {
  _FakeOrignaBasePresence_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseLinks_7 extends _i1.SmartFake
    implements _i9.OrignaBaseLinks {
  _FakeOrignaBaseLinks_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePush_8 extends _i1.SmartFake
    implements _i10.OrignaBasePush {
  _FakeOrignaBasePush_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseMetrics_9 extends _i1.SmartFake
    implements _i11.OrignaBaseMetrics {
  _FakeOrignaBaseMetrics_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVectorSearch_10 extends _i1.SmartFake implements _i12.VectorSearch {
  _FakeVectorSearch_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_11 extends _i1.SmartFake
    implements _i13.RealtimeClient {
  _FakeRealtimeClient_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionRef_12 extends _i1.SmartFake
    implements _i14.CollectionRef {
  _FakeCollectionRef_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_13 extends _i1.SmartFake implements _i15.WriteBatch {
  _FakeWriteBatch_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthState_14 extends _i1.SmartFake implements _i4.AuthState {
  _FakeAuthState_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaSetupResult_15 extends _i1.SmartFake
    implements _i4.MfaSetupResult {
  _FakeMfaSetupResult_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i16.OrderRepository {
  @override
  _i17.Future<void> approveShippingCost(String? orderId, bool? approved) =>
      (super.noSuchMethod(
            Invocation.method(#approveShippingCost, [orderId, approved]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> capturePayment(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#capturePayment, [orderId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> confirmReceipt(String? orderId, {String? productId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmReceipt,
              [orderId],
              {#productId: productId},
            ),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<Map<String, dynamic>> createCheckoutSession(
    Map<String, dynamic>? orderData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCheckoutSession, [orderData]),
            returnValue: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i17.Future<Map<String, dynamic>>);

  @override
  _i17.Future<_i18.Order?> fetchOrderById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i17.Future<_i18.Order?>.value(),
            returnValueForMissingStub: _i17.Future<_i18.Order?>.value(),
          )
          as _i17.Future<_i18.Order?>);

  @override
  _i17.Future<void> updateItemStatus(
    String? orderId,
    String? itemId,
    String? status, {
    String? trackingNumber,
    String? carrier,
    String? carrierNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateItemStatus,
              [orderId, itemId, status],
              {
                #trackingNumber: trackingNumber,
                #carrier: carrier,
                #carrierNote: carrierNote,
              },
            ),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> updateLastSession(
    String? userId,
    String? sessionId,
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSession, [userId, sessionId, orderId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> updateShippingCost(
    String? orderId,
    int? newShippingCostCents,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShippingCost, [
              orderId,
              newShippingCostCents,
              reason,
            ]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Stream<List<_i18.Order>> watchBuyerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBuyerOrders, [userId]),
            returnValue: _i17.Stream<List<_i18.Order>>.empty(),
            returnValueForMissingStub: _i17.Stream<List<_i18.Order>>.empty(),
          )
          as _i17.Stream<List<_i18.Order>>);

  @override
  _i17.Stream<_i18.Order?> watchPaidOrderBySession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPaidOrderBySession, [sessionId]),
            returnValue: _i17.Stream<_i18.Order?>.empty(),
            returnValueForMissingStub: _i17.Stream<_i18.Order?>.empty(),
          )
          as _i17.Stream<_i18.Order?>);

  @override
  _i17.Stream<List<_i18.Order>> watchSellerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerOrders, [userId]),
            returnValue: _i17.Stream<List<_i18.Order>>.empty(),
            returnValueForMissingStub: _i17.Stream<List<_i18.Order>>.empty(),
          )
          as _i17.Stream<List<_i18.Order>>);

  @override
  _i17.Future<Map<String, dynamic>> createReturnRequest({
    required String? orderId,
    required List<String>? cartItemIds,
    required String? reason,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReturnRequest, [], {
              #orderId: orderId,
              #cartItemIds: cartItemIds,
              #reason: reason,
              #description: description,
            }),
            returnValue: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i17.Future<Map<String, dynamic>>);

  @override
  _i17.Future<List<_i18.ReturnRequest>> fetchReturnRequests(
    String? orderId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchReturnRequests,
              [orderId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i17.Future<List<_i18.ReturnRequest>>.value(
              <_i18.ReturnRequest>[],
            ),
            returnValueForMissingStub:
                _i17.Future<List<_i18.ReturnRequest>>.value(
                  <_i18.ReturnRequest>[],
                ),
          )
          as _i17.Future<List<_i18.ReturnRequest>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  @override
  _i17.Future<String> addBuyerAddress(_i19.Address? address) =>
      (super.noSuchMethod(
            Invocation.method(#addBuyerAddress, [address]),
            returnValue: _i17.Future<String>.value(
              _i20.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
            returnValueForMissingStub: _i17.Future<String>.value(
              _i20.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
          )
          as _i17.Future<String>);

  @override
  _i17.Future<void> deleteBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBuyerAddress, [addressId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<_i2.SellerAccountStatus> getSellerAccountStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getSellerAccountStatus, [userId]),
            returnValue: _i17.Future<_i2.SellerAccountStatus>.value(
              _FakeSellerAccountStatus_0(
                this,
                Invocation.method(#getSellerAccountStatus, [userId]),
              ),
            ),
            returnValueForMissingStub:
                _i17.Future<_i2.SellerAccountStatus>.value(
                  _FakeSellerAccountStatus_0(
                    this,
                    Invocation.method(#getSellerAccountStatus, [userId]),
                  ),
                ),
          )
          as _i17.Future<_i2.SellerAccountStatus>);

  @override
  _i17.Future<_i19.UserModel?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i17.Future<_i19.UserModel?>.value(),
            returnValueForMissingStub: _i17.Future<_i19.UserModel?>.value(),
          )
          as _i17.Future<_i19.UserModel?>);

  @override
  _i17.Future<void> recordTermsAcceptance() =>
      (super.noSuchMethod(
            Invocation.method(#recordTermsAcceptance, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> setDefaultBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultBuyerAddress, [addressId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> updateBuyerAddress(
    String? addressId,
    _i19.Address? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerAddress, [addressId, address]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> updateNotificationPreferences(
    String? userId, {
    bool? notifyNewProducts,
    bool? notifyTrending,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNotificationPreferences,
              [userId],
              {
                #notifyNewProducts: notifyNewProducts,
                #notifyTrending: notifyTrending,
              },
            ),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> updatePreferredLanguage(String? userId, String? lang) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferredLanguage, [userId, lang]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Stream<List<_i19.Address>> watchAddresses(
    String? userId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchAddresses,
              [userId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i17.Stream<List<_i19.Address>>.empty(),
            returnValueForMissingStub: _i17.Stream<List<_i19.Address>>.empty(),
          )
          as _i17.Stream<List<_i19.Address>>);

  @override
  _i17.Stream<_i2.SellerAccountStatus> watchSellerAccountStatus(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerAccountStatus, [userId]),
            returnValue: _i17.Stream<_i2.SellerAccountStatus>.empty(),
            returnValueForMissingStub:
                _i17.Stream<_i2.SellerAccountStatus>.empty(),
          )
          as _i17.Stream<_i2.SellerAccountStatus>);
}

/// A class which mocks [OrignaBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrignaBase extends _i1.Mock implements _i21.OrignaBase {
  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i20.dummyValue<String>(this, Invocation.getter(#url)),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.getter(#url),
            ),
          )
          as String);

  @override
  _i3.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_1(this, Invocation.getter(#httpClient)),
            returnValueForMissingStub: _FakeClient_1(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i3.Client);

  @override
  _i4.OrignaBaseAuth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeOrignaBaseAuth_2(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeOrignaBaseAuth_2(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i4.OrignaBaseAuth);

  @override
  _i5.OrignaBaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeOrignaBaseStorage_3(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeOrignaBaseStorage_3(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i5.OrignaBaseStorage);

  @override
  _i6.OfflineCache get offline =>
      (super.noSuchMethod(
            Invocation.getter(#offline),
            returnValue: _FakeOfflineCache_4(this, Invocation.getter(#offline)),
            returnValueForMissingStub: _FakeOfflineCache_4(
              this,
              Invocation.getter(#offline),
            ),
          )
          as _i6.OfflineCache);

  @override
  _i7.OrignaBaseConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeOrignaBaseConfig_5(
              this,
              Invocation.getter(#config),
            ),
            returnValueForMissingStub: _FakeOrignaBaseConfig_5(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i7.OrignaBaseConfig);

  @override
  _i8.OrignaBasePresence get presence =>
      (super.noSuchMethod(
            Invocation.getter(#presence),
            returnValue: _FakeOrignaBasePresence_6(
              this,
              Invocation.getter(#presence),
            ),
            returnValueForMissingStub: _FakeOrignaBasePresence_6(
              this,
              Invocation.getter(#presence),
            ),
          )
          as _i8.OrignaBasePresence);

  @override
  _i9.OrignaBaseLinks get links =>
      (super.noSuchMethod(
            Invocation.getter(#links),
            returnValue: _FakeOrignaBaseLinks_7(
              this,
              Invocation.getter(#links),
            ),
            returnValueForMissingStub: _FakeOrignaBaseLinks_7(
              this,
              Invocation.getter(#links),
            ),
          )
          as _i9.OrignaBaseLinks);

  @override
  _i10.OrignaBasePush get push =>
      (super.noSuchMethod(
            Invocation.getter(#push),
            returnValue: _FakeOrignaBasePush_8(this, Invocation.getter(#push)),
            returnValueForMissingStub: _FakeOrignaBasePush_8(
              this,
              Invocation.getter(#push),
            ),
          )
          as _i10.OrignaBasePush);

  @override
  _i11.OrignaBaseMetrics get metrics =>
      (super.noSuchMethod(
            Invocation.getter(#metrics),
            returnValue: _FakeOrignaBaseMetrics_9(
              this,
              Invocation.getter(#metrics),
            ),
            returnValueForMissingStub: _FakeOrignaBaseMetrics_9(
              this,
              Invocation.getter(#metrics),
            ),
          )
          as _i11.OrignaBaseMetrics);

  @override
  _i12.VectorSearch get vectorSearch =>
      (super.noSuchMethod(
            Invocation.getter(#vectorSearch),
            returnValue: _FakeVectorSearch_10(
              this,
              Invocation.getter(#vectorSearch),
            ),
            returnValueForMissingStub: _FakeVectorSearch_10(
              this,
              Invocation.getter(#vectorSearch),
            ),
          )
          as _i12.VectorSearch);

  @override
  _i13.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_11(
              this,
              Invocation.getter(#realtime),
            ),
            returnValueForMissingStub: _FakeRealtimeClient_11(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i13.RealtimeClient);

  @override
  set auth(_i4.OrignaBaseAuth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i5.OrignaBaseStorage? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set offline(_i6.OfflineCache? value) => super.noSuchMethod(
    Invocation.setter(#offline, value),
    returnValueForMissingStub: null,
  );

  @override
  set config(_i7.OrignaBaseConfig? value) => super.noSuchMethod(
    Invocation.setter(#config, value),
    returnValueForMissingStub: null,
  );

  @override
  set presence(_i8.OrignaBasePresence? value) => super.noSuchMethod(
    Invocation.setter(#presence, value),
    returnValueForMissingStub: null,
  );

  @override
  set links(_i9.OrignaBaseLinks? value) => super.noSuchMethod(
    Invocation.setter(#links, value),
    returnValueForMissingStub: null,
  );

  @override
  set push(_i10.OrignaBasePush? value) => super.noSuchMethod(
    Invocation.setter(#push, value),
    returnValueForMissingStub: null,
  );

  @override
  set metrics(_i11.OrignaBaseMetrics? value) => super.noSuchMethod(
    Invocation.setter(#metrics, value),
    returnValueForMissingStub: null,
  );

  @override
  set vectorSearch(_i12.VectorSearch? value) => super.noSuchMethod(
    Invocation.setter(#vectorSearch, value),
    returnValueForMissingStub: null,
  );

  @override
  _i14.CollectionRef collection(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [name]),
            returnValue: _FakeCollectionRef_12(
              this,
              Invocation.method(#collection, [name]),
            ),
            returnValueForMissingStub: _FakeCollectionRef_12(
              this,
              Invocation.method(#collection, [name]),
            ),
          )
          as _i14.CollectionRef);

  @override
  _i15.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_13(
              this,
              Invocation.method(#batch, []),
            ),
            returnValueForMissingStub: _FakeWriteBatch_13(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i15.WriteBatch);

  @override
  _i17.Future<Map<String, dynamic>> graphql(
    String? query, {
    Map<String, dynamic>? variables,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#graphql, [query], {#variables: variables}),
            returnValue: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i17.Future<Map<String, dynamic>>);

  @override
  _i17.Future<Map<String, dynamic>> request(
    String? method,
    String? path, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [method, path],
              {#body: body, #headers: headers},
            ),
            returnValue: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i17.Future<Map<String, dynamic>>);

  @override
  _i17.Future<Map<String, dynamic>> search(
    String? index,
    String? query, {
    int? limit,
    int? offset,
    String? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [index, query],
              {#limit: limit, #offset: offset, #filter: filter},
            ),
            returnValue: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i17.Future<Map<String, dynamic>>);

  @override
  void closeRealtime() => super.noSuchMethod(
    Invocation.method(#closeRealtime, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OrignaBaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrignaBaseAuth extends _i1.Mock implements _i4.OrignaBaseAuth {
  @override
  _i17.Stream<_i4.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i17.Stream<_i4.AuthState>.empty(),
            returnValueForMissingStub: _i17.Stream<_i4.AuthState>.empty(),
          )
          as _i17.Stream<_i4.AuthState>);

  @override
  Map<String, dynamic> get currentClaims =>
      (super.noSuchMethod(
            Invocation.getter(#currentClaims),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<String> get currentRoles =>
      (super.noSuchMethod(
            Invocation.getter(#currentRoles),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get isEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isEmailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.AuthState get currentState =>
      (super.noSuchMethod(
            Invocation.getter(#currentState),
            returnValue: _FakeAuthState_14(
              this,
              Invocation.getter(#currentState),
            ),
            returnValueForMissingStub: _FakeAuthState_14(
              this,
              Invocation.getter(#currentState),
            ),
          )
          as _i4.AuthState);

  @override
  _i17.Future<_i4.AuthState> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#register, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#register, [email, password]),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<_i4.AuthState> signInWithEmail(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<_i4.AuthState> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(this, Invocation.method(#refreshToken, [])),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(this, Invocation.method(#refreshToken, [])),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<_i4.AuthState> signInWithGoogle(String? idToken) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, [idToken]),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#signInWithGoogle, [idToken]),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#signInWithGoogle, [idToken]),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<_i4.AuthState> signInWithApple(
    String? authorizationCode, {
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #signInWithApple,
              [authorizationCode],
              {#displayName: displayName},
            ),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(
                  #signInWithApple,
                  [authorizationCode],
                  {#displayName: displayName},
                ),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(
                  #signInWithApple,
                  [authorizationCode],
                  {#displayName: displayName},
                ),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<_i4.AuthState> signInWithOidc(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOidc, [accessToken]),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#signInWithOidc, [accessToken]),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#signInWithOidc, [accessToken]),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<void> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> resetPassword(String? token, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [token, newPassword]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<_i4.AuthState> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<_i4.AuthState> upgradeAnonymous(
    String? email,
    String? password, {
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upgradeAnonymous,
              [email, password],
              {#displayName: displayName},
            ),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(
                  #upgradeAnonymous,
                  [email, password],
                  {#displayName: displayName},
                ),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(
                  #upgradeAnonymous,
                  [email, password],
                  {#displayName: displayName},
                ),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<void> sendMagicLink(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendMagicLink, [email]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<_i4.AuthState> verifyMagicLink(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMagicLink, [token]),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#verifyMagicLink, [token]),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#verifyMagicLink, [token]),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> verifyEmail(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [token]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<_i4.MfaSetupResult> setupMfa() =>
      (super.noSuchMethod(
            Invocation.method(#setupMfa, []),
            returnValue: _i17.Future<_i4.MfaSetupResult>.value(
              _FakeMfaSetupResult_15(this, Invocation.method(#setupMfa, [])),
            ),
            returnValueForMissingStub: _i17.Future<_i4.MfaSetupResult>.value(
              _FakeMfaSetupResult_15(this, Invocation.method(#setupMfa, [])),
            ),
          )
          as _i17.Future<_i4.MfaSetupResult>);

  @override
  _i17.Future<List<String>> verifyMfaSetup(String? totpCode) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMfaSetup, [totpCode]),
            returnValue: _i17.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i17.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i17.Future<List<String>>);

  @override
  _i17.Future<_i4.AuthState> verifyMfaChallenge(
    String? challengeToken,
    String? totpCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMfaChallenge, [challengeToken, totpCode]),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#verifyMfaChallenge, [
                  challengeToken,
                  totpCode,
                ]),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#verifyMfaChallenge, [
                  challengeToken,
                  totpCode,
                ]),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<_i4.AuthState> useMfaRecoveryCode(
    String? challengeToken,
    String? recoveryCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#useMfaRecoveryCode, [
              challengeToken,
              recoveryCode,
            ]),
            returnValue: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#useMfaRecoveryCode, [
                  challengeToken,
                  recoveryCode,
                ]),
              ),
            ),
            returnValueForMissingStub: _i17.Future<_i4.AuthState>.value(
              _FakeAuthState_14(
                this,
                Invocation.method(#useMfaRecoveryCode, [
                  challengeToken,
                  recoveryCode,
                ]),
              ),
            ),
          )
          as _i17.Future<_i4.AuthState>);

  @override
  _i17.Future<void> disableMfa(String? totpCode) =>
      (super.noSuchMethod(
            Invocation.method(#disableMfa, [totpCode]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<List<Map<String, dynamic>>> getLoginHistory({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLoginHistory, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i17.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i17.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i17.Future<List<Map<String, dynamic>>>);

  @override
  _i17.Future<List<Map<String, dynamic>>> getKnownDevices() =>
      (super.noSuchMethod(
            Invocation.method(#getKnownDevices, []),
            returnValue: _i17.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i17.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i17.Future<List<Map<String, dynamic>>>);

  @override
  _i17.Future<void> removeDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#removeDevice, [deviceId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<List<Map<String, dynamic>>> getSecurityAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#getSecurityAlerts, []),
            returnValue: _i17.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i17.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i17.Future<List<Map<String, dynamic>>>);

  @override
  _i17.Future<void> acknowledgeAlert(String? alertId) =>
      (super.noSuchMethod(
            Invocation.method(#acknowledgeAlert, [alertId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i4.AuthState restoreSession({
    required String? accessToken,
    String? refreshToken,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #email: email,
            }),
            returnValue: _FakeAuthState_14(
              this,
              Invocation.method(#restoreSession, [], {
                #accessToken: accessToken,
                #refreshToken: refreshToken,
                #email: email,
              }),
            ),
            returnValueForMissingStub: _FakeAuthState_14(
              this,
              Invocation.method(#restoreSession, [], {
                #accessToken: accessToken,
                #refreshToken: refreshToken,
                #email: email,
              }),
            ),
          )
          as _i4.AuthState);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
