// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/unit/checkout_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;

import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:origna_gta/core/repositories/order_repository.dart' as _i15;
import 'package:origna_gta/core/repositories/user_repository.dart' as _i2;
import 'package:origna_gta/models/generated/models.dart' as _i17;
import 'package:origna_gta/utils/utils.dart' as _i18;
import 'package:orignabase/src/auth.dart' as _i4;
import 'package:orignabase/src/batch.dart' as _i14;
import 'package:orignabase/src/client.dart' as _i20;
import 'package:orignabase/src/collection.dart' as _i13;
import 'package:orignabase/src/config.dart' as _i7;
import 'package:orignabase/src/links.dart' as _i9;
import 'package:orignabase/src/metrics.dart' as _i11;
import 'package:orignabase/src/offline.dart' as _i6;
import 'package:orignabase/src/presence.dart' as _i8;
import 'package:orignabase/src/push.dart' as _i10;
import 'package:orignabase/src/storage.dart' as _i5;
import 'package:orignabase/src/vector.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSellerAccountStatus_0 extends _i1.SmartFake
    implements _i2.SellerAccountStatus {
  _FakeSellerAccountStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseAuth_2 extends _i1.SmartFake
    implements _i4.OrignaBaseAuth {
  _FakeOrignaBaseAuth_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseStorage_3 extends _i1.SmartFake
    implements _i5.OrignaBaseStorage {
  _FakeOrignaBaseStorage_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfflineCache_4 extends _i1.SmartFake implements _i6.OfflineCache {
  _FakeOfflineCache_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseConfig_5 extends _i1.SmartFake
    implements _i7.OrignaBaseConfig {
  _FakeOrignaBaseConfig_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePresence_6 extends _i1.SmartFake
    implements _i8.OrignaBasePresence {
  _FakeOrignaBasePresence_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseLinks_7 extends _i1.SmartFake
    implements _i9.OrignaBaseLinks {
  _FakeOrignaBaseLinks_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePush_8 extends _i1.SmartFake
    implements _i10.OrignaBasePush {
  _FakeOrignaBasePush_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseMetrics_9 extends _i1.SmartFake
    implements _i11.OrignaBaseMetrics {
  _FakeOrignaBaseMetrics_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVectorSearch_10 extends _i1.SmartFake implements _i12.VectorSearch {
  _FakeVectorSearch_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionRef_11 extends _i1.SmartFake
    implements _i13.CollectionRef {
  _FakeCollectionRef_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_12 extends _i1.SmartFake implements _i14.WriteBatch {
  _FakeWriteBatch_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i15.OrderRepository {
  @override
  _i16.Future<void> approveShippingCost(String? orderId, bool? approved) =>
      (super.noSuchMethod(
            Invocation.method(#approveShippingCost, [orderId, approved]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> capturePayment(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#capturePayment, [orderId]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> confirmReceipt(String? orderId, {String? productId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmReceipt,
              [orderId],
              {#productId: productId},
            ),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<Map<String, dynamic>> createCheckoutSession(
    Map<String, dynamic>? orderData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCheckoutSession, [orderData]),
            returnValue: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i16.Future<Map<String, dynamic>>);

  @override
  _i16.Future<_i17.Order?> fetchOrderById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i16.Future<_i17.Order?>.value(),
            returnValueForMissingStub: _i16.Future<_i17.Order?>.value(),
          )
          as _i16.Future<_i17.Order?>);

  @override
  _i16.Future<void> updateItemStatus(
    String? orderId,
    String? itemId,
    String? status, {
    String? trackingNumber,
    String? carrier,
    String? carrierNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateItemStatus,
              [orderId, itemId, status],
              {
                #trackingNumber: trackingNumber,
                #carrier: carrier,
                #carrierNote: carrierNote,
              },
            ),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> updateLastSession(
    String? userId,
    String? sessionId,
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSession, [userId, sessionId, orderId]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> updateShippingCost(
    String? orderId,
    double? newShippingCost,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShippingCost, [
              orderId,
              newShippingCost,
              reason,
            ]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Stream<List<_i17.Order>> watchBuyerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBuyerOrders, [userId]),
            returnValue: _i16.Stream<List<_i17.Order>>.empty(),
            returnValueForMissingStub: _i16.Stream<List<_i17.Order>>.empty(),
          )
          as _i16.Stream<List<_i17.Order>>);

  @override
  _i16.Stream<_i17.Order?> watchPaidOrderBySession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPaidOrderBySession, [sessionId]),
            returnValue: _i16.Stream<_i17.Order?>.empty(),
            returnValueForMissingStub: _i16.Stream<_i17.Order?>.empty(),
          )
          as _i16.Stream<_i17.Order?>);

  @override
  _i16.Stream<List<_i17.Order>> watchSellerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerOrders, [userId]),
            returnValue: _i16.Stream<List<_i17.Order>>.empty(),
            returnValueForMissingStub: _i16.Stream<List<_i17.Order>>.empty(),
          )
          as _i16.Stream<List<_i17.Order>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  @override
  _i16.Future<String> addBuyerAddress(_i18.Address? address) =>
      (super.noSuchMethod(
            Invocation.method(#addBuyerAddress, [address]),
            returnValue: _i16.Future<String>.value(
              _i19.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
            returnValueForMissingStub: _i16.Future<String>.value(
              _i19.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<void> deleteBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBuyerAddress, [addressId]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<_i2.SellerAccountStatus> getSellerAccountStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getSellerAccountStatus, [userId]),
            returnValue: _i16.Future<_i2.SellerAccountStatus>.value(
              _FakeSellerAccountStatus_0(
                this,
                Invocation.method(#getSellerAccountStatus, [userId]),
              ),
            ),
            returnValueForMissingStub:
                _i16.Future<_i2.SellerAccountStatus>.value(
                  _FakeSellerAccountStatus_0(
                    this,
                    Invocation.method(#getSellerAccountStatus, [userId]),
                  ),
                ),
          )
          as _i16.Future<_i2.SellerAccountStatus>);

  @override
  _i16.Future<_i18.UserModel?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i16.Future<_i18.UserModel?>.value(),
            returnValueForMissingStub: _i16.Future<_i18.UserModel?>.value(),
          )
          as _i16.Future<_i18.UserModel?>);

  @override
  _i16.Future<void> recordTermsAcceptance() =>
      (super.noSuchMethod(
            Invocation.method(#recordTermsAcceptance, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> setDefaultBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultBuyerAddress, [addressId]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> updateBuyerAddress(
    String? addressId,
    _i18.Address? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerAddress, [addressId, address]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> updateNotificationPreferences(
    String? userId, {
    bool? notifyNewProducts,
    bool? notifyTrending,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNotificationPreferences,
              [userId],
              {
                #notifyNewProducts: notifyNewProducts,
                #notifyTrending: notifyTrending,
              },
            ),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> updatePreferredLanguage(String? userId, String? lang) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferredLanguage, [userId, lang]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Stream<List<_i18.Address>> watchAddresses(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchAddresses, [userId]),
            returnValue: _i16.Stream<List<_i18.Address>>.empty(),
            returnValueForMissingStub: _i16.Stream<List<_i18.Address>>.empty(),
          )
          as _i16.Stream<List<_i18.Address>>);

  @override
  _i16.Stream<_i2.SellerAccountStatus> watchSellerAccountStatus(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerAccountStatus, [userId]),
            returnValue: _i16.Stream<_i2.SellerAccountStatus>.empty(),
            returnValueForMissingStub:
                _i16.Stream<_i2.SellerAccountStatus>.empty(),
          )
          as _i16.Stream<_i2.SellerAccountStatus>);
}

/// A class which mocks [OrignaBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrignaBase extends _i1.Mock implements _i20.OrignaBase {
  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i19.dummyValue<String>(this, Invocation.getter(#url)),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#url),
            ),
          )
          as String);

  @override
  _i3.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_1(this, Invocation.getter(#httpClient)),
            returnValueForMissingStub: _FakeClient_1(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i3.Client);

  @override
  _i4.OrignaBaseAuth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeOrignaBaseAuth_2(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeOrignaBaseAuth_2(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i4.OrignaBaseAuth);

  @override
  _i5.OrignaBaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeOrignaBaseStorage_3(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeOrignaBaseStorage_3(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i5.OrignaBaseStorage);

  @override
  _i6.OfflineCache get offline =>
      (super.noSuchMethod(
            Invocation.getter(#offline),
            returnValue: _FakeOfflineCache_4(this, Invocation.getter(#offline)),
            returnValueForMissingStub: _FakeOfflineCache_4(
              this,
              Invocation.getter(#offline),
            ),
          )
          as _i6.OfflineCache);

  @override
  _i7.OrignaBaseConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeOrignaBaseConfig_5(
              this,
              Invocation.getter(#config),
            ),
            returnValueForMissingStub: _FakeOrignaBaseConfig_5(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i7.OrignaBaseConfig);

  @override
  _i8.OrignaBasePresence get presence =>
      (super.noSuchMethod(
            Invocation.getter(#presence),
            returnValue: _FakeOrignaBasePresence_6(
              this,
              Invocation.getter(#presence),
            ),
            returnValueForMissingStub: _FakeOrignaBasePresence_6(
              this,
              Invocation.getter(#presence),
            ),
          )
          as _i8.OrignaBasePresence);

  @override
  _i9.OrignaBaseLinks get links =>
      (super.noSuchMethod(
            Invocation.getter(#links),
            returnValue: _FakeOrignaBaseLinks_7(
              this,
              Invocation.getter(#links),
            ),
            returnValueForMissingStub: _FakeOrignaBaseLinks_7(
              this,
              Invocation.getter(#links),
            ),
          )
          as _i9.OrignaBaseLinks);

  @override
  _i10.OrignaBasePush get push =>
      (super.noSuchMethod(
            Invocation.getter(#push),
            returnValue: _FakeOrignaBasePush_8(this, Invocation.getter(#push)),
            returnValueForMissingStub: _FakeOrignaBasePush_8(
              this,
              Invocation.getter(#push),
            ),
          )
          as _i10.OrignaBasePush);

  @override
  _i11.OrignaBaseMetrics get metrics =>
      (super.noSuchMethod(
            Invocation.getter(#metrics),
            returnValue: _FakeOrignaBaseMetrics_9(
              this,
              Invocation.getter(#metrics),
            ),
            returnValueForMissingStub: _FakeOrignaBaseMetrics_9(
              this,
              Invocation.getter(#metrics),
            ),
          )
          as _i11.OrignaBaseMetrics);

  @override
  _i12.VectorSearch get vectorSearch =>
      (super.noSuchMethod(
            Invocation.getter(#vectorSearch),
            returnValue: _FakeVectorSearch_10(
              this,
              Invocation.getter(#vectorSearch),
            ),
            returnValueForMissingStub: _FakeVectorSearch_10(
              this,
              Invocation.getter(#vectorSearch),
            ),
          )
          as _i12.VectorSearch);

  @override
  set auth(_i4.OrignaBaseAuth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i5.OrignaBaseStorage? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set offline(_i6.OfflineCache? value) => super.noSuchMethod(
    Invocation.setter(#offline, value),
    returnValueForMissingStub: null,
  );

  @override
  set config(_i7.OrignaBaseConfig? value) => super.noSuchMethod(
    Invocation.setter(#config, value),
    returnValueForMissingStub: null,
  );

  @override
  set presence(_i8.OrignaBasePresence? value) => super.noSuchMethod(
    Invocation.setter(#presence, value),
    returnValueForMissingStub: null,
  );

  @override
  set links(_i9.OrignaBaseLinks? value) => super.noSuchMethod(
    Invocation.setter(#links, value),
    returnValueForMissingStub: null,
  );

  @override
  set push(_i10.OrignaBasePush? value) => super.noSuchMethod(
    Invocation.setter(#push, value),
    returnValueForMissingStub: null,
  );

  @override
  set metrics(_i11.OrignaBaseMetrics? value) => super.noSuchMethod(
    Invocation.setter(#metrics, value),
    returnValueForMissingStub: null,
  );

  @override
  set vectorSearch(_i12.VectorSearch? value) => super.noSuchMethod(
    Invocation.setter(#vectorSearch, value),
    returnValueForMissingStub: null,
  );

  @override
  _i13.CollectionRef collection(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [name]),
            returnValue: _FakeCollectionRef_11(
              this,
              Invocation.method(#collection, [name]),
            ),
            returnValueForMissingStub: _FakeCollectionRef_11(
              this,
              Invocation.method(#collection, [name]),
            ),
          )
          as _i13.CollectionRef);

  @override
  _i14.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_12(
              this,
              Invocation.method(#batch, []),
            ),
            returnValueForMissingStub: _FakeWriteBatch_12(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i14.WriteBatch);

  @override
  _i16.Future<Map<String, dynamic>> graphql(
    String? query, {
    Map<String, dynamic>? variables,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#graphql, [query], {#variables: variables}),
            returnValue: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i16.Future<Map<String, dynamic>>);

  @override
  _i16.Future<Map<String, dynamic>> request(
    String? method,
    String? path, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [method, path],
              {#body: body, #headers: headers},
            ),
            returnValue: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i16.Future<Map<String, dynamic>>);

  @override
  _i16.Future<Map<String, dynamic>> search(
    String? index,
    String? query, {
    int? limit,
    int? offset,
    String? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [index, query],
              {#limit: limit, #offset: offset, #filter: filter},
            ),
            returnValue: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i16.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
