// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/unit/notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i21;
import 'dart:ui' as _i24;

import 'package:flutter/foundation.dart' as _i4;
import 'package:flutter/scheduler.dart' as _i7;
import 'package:flutter/services.dart' as _i22;
import 'package:flutter/src/material/banner.dart' as _i28;
import 'package:flutter/src/material/scaffold.dart' as _i8;
import 'package:flutter/src/material/snack_bar.dart' as _i26;
import 'package:flutter/src/widgets/basic.dart' as _i27;
import 'package:flutter/src/widgets/focus_manager.dart' as _i3;
import 'package:flutter/src/widgets/framework.dart' as _i6;
import 'package:flutter/src/widgets/restoration.dart' as _i25;
import 'package:flutter/widgets.dart' as _i5;
import 'package:http/http.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i23;
import 'package:origna_gta/services/push_transport.dart' as _i2;
import 'package:orignabase/src/auth.dart' as _i10;
import 'package:orignabase/src/batch.dart' as _i20;
import 'package:orignabase/src/client.dart' as _i29;
import 'package:orignabase/src/collection.dart' as _i19;
import 'package:orignabase/src/config.dart' as _i13;
import 'package:orignabase/src/links.dart' as _i15;
import 'package:orignabase/src/metrics.dart' as _i17;
import 'package:orignabase/src/offline.dart' as _i12;
import 'package:orignabase/src/presence.dart' as _i14;
import 'package:orignabase/src/push.dart' as _i16;
import 'package:orignabase/src/storage.dart' as _i11;
import 'package:orignabase/src/vector.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppNotificationSettings_0 extends _i1.SmartFake
    implements _i2.AppNotificationSettings {
  _FakeAppNotificationSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFocusNode_1 extends _i1.SmartFake implements _i3.FocusNode {
  _FakeFocusNode_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigator_3 extends _i1.SmartFake implements _i5.Navigator {
  _FakeNavigator_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeBuildContext_4 extends _i1.SmartFake implements _i6.BuildContext {
  _FakeBuildContext_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_5 extends _i1.SmartFake implements _i6.Widget {
  _FakeWidget_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_6 extends _i1.SmartFake
    implements _i4.DiagnosticsNode {
  _FakeDiagnosticsNode_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i4.TextTreeConfiguration? parentConfiguration,
    _i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info,
  }) => super.toString();
}

class _FakeTicker_7 extends _i1.SmartFake implements _i7.Ticker {
  _FakeTicker_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({bool? debugIncludeStack = false}) => super.toString();
}

class _FakeScaffoldMessenger_8 extends _i1.SmartFake
    implements _i8.ScaffoldMessenger {
  _FakeScaffoldMessenger_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeScaffoldFeatureController_9<T extends _i6.Widget, U>
    extends _i1.SmartFake
    implements _i8.ScaffoldFeatureController<T, U> {
  _FakeScaffoldFeatureController_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_10 extends _i1.SmartFake implements _i9.Client {
  _FakeClient_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseAuth_11 extends _i1.SmartFake
    implements _i10.OrignaBaseAuth {
  _FakeOrignaBaseAuth_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseStorage_12 extends _i1.SmartFake
    implements _i11.OrignaBaseStorage {
  _FakeOrignaBaseStorage_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfflineCache_13 extends _i1.SmartFake implements _i12.OfflineCache {
  _FakeOfflineCache_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseConfig_14 extends _i1.SmartFake
    implements _i13.OrignaBaseConfig {
  _FakeOrignaBaseConfig_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePresence_15 extends _i1.SmartFake
    implements _i14.OrignaBasePresence {
  _FakeOrignaBasePresence_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseLinks_16 extends _i1.SmartFake
    implements _i15.OrignaBaseLinks {
  _FakeOrignaBaseLinks_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePush_17 extends _i1.SmartFake
    implements _i16.OrignaBasePush {
  _FakeOrignaBasePush_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseMetrics_18 extends _i1.SmartFake
    implements _i17.OrignaBaseMetrics {
  _FakeOrignaBaseMetrics_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVectorSearch_19 extends _i1.SmartFake implements _i18.VectorSearch {
  _FakeVectorSearch_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionRef_20 extends _i1.SmartFake
    implements _i19.CollectionRef {
  _FakeCollectionRef_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_21 extends _i1.SmartFake implements _i20.WriteBatch {
  _FakeWriteBatch_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePushResult_22 extends _i1.SmartFake implements _i16.PushResult {
  _FakePushResult_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PushMessagingClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushMessagingClient extends _i1.Mock
    implements _i2.PushMessagingClient {
  @override
  _i21.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(
            Invocation.getter(#onTokenRefresh),
            returnValue: _i21.Stream<String>.empty(),
            returnValueForMissingStub: _i21.Stream<String>.empty(),
          )
          as _i21.Stream<String>);

  @override
  _i21.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i21.Future<String?>.value(),
            returnValueForMissingStub: _i21.Future<String?>.value(),
          )
          as _i21.Future<String?>);

  @override
  _i21.Future<_i2.AppRemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessage, []),
            returnValue: _i21.Future<_i2.AppRemoteMessage?>.value(),
            returnValueForMissingStub:
                _i21.Future<_i2.AppRemoteMessage?>.value(),
          )
          as _i21.Future<_i2.AppRemoteMessage?>);

  @override
  _i21.Future<_i2.AppNotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, [], {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
            }),
            returnValue: _i21.Future<_i2.AppNotificationSettings>.value(
              _FakeAppNotificationSettings_0(
                this,
                Invocation.method(#requestPermission, [], {
                  #alert: alert,
                  #announcement: announcement,
                  #badge: badge,
                  #carPlay: carPlay,
                  #criticalAlert: criticalAlert,
                  #provisional: provisional,
                  #sound: sound,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i21.Future<_i2.AppNotificationSettings>.value(
                  _FakeAppNotificationSettings_0(
                    this,
                    Invocation.method(#requestPermission, [], {
                      #alert: alert,
                      #announcement: announcement,
                      #badge: badge,
                      #carPlay: carPlay,
                      #criticalAlert: criticalAlert,
                      #provisional: provisional,
                      #sound: sound,
                    }),
                  ),
                ),
          )
          as _i21.Future<_i2.AppNotificationSettings>);
}

/// A class which mocks [NavigatorState].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorState extends _i1.Mock implements _i5.NavigatorState {
  @override
  _i3.FocusNode get focusNode =>
      (super.noSuchMethod(
            Invocation.getter(#focusNode),
            returnValue: _FakeFocusNode_1(this, Invocation.getter(#focusNode)),
            returnValueForMissingStub: _FakeFocusNode_1(
              this,
              Invocation.getter(#focusNode),
            ),
          )
          as _i3.FocusNode);

  @override
  bool get userGestureInProgress =>
      (super.noSuchMethod(
            Invocation.getter(#userGestureInProgress),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.ValueNotifier<bool> get userGestureInProgressNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#userGestureInProgressNotifier),
            returnValue: _FakeValueNotifier_2<bool>(
              this,
              Invocation.getter(#userGestureInProgressNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<bool>(
              this,
              Invocation.getter(#userGestureInProgressNotifier),
            ),
          )
          as _i4.ValueNotifier<bool>);

  @override
  _i5.Navigator get widget =>
      (super.noSuchMethod(
            Invocation.getter(#widget),
            returnValue: _FakeNavigator_3(this, Invocation.getter(#widget)),
            returnValueForMissingStub: _FakeNavigator_3(
              this,
              Invocation.getter(#widget),
            ),
          )
          as _i5.Navigator);

  @override
  _i6.BuildContext get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _FakeBuildContext_4(this, Invocation.getter(#context)),
            returnValueForMissingStub: _FakeBuildContext_4(
              this,
              Invocation.getter(#context),
            ),
          )
          as _i6.BuildContext);

  @override
  bool get mounted =>
      (super.noSuchMethod(
            Invocation.getter(#mounted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get restorePending =>
      (super.noSuchMethod(
            Invocation.getter(#restorePending),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void initState() => super.noSuchMethod(
    Invocation.method(#initState, []),
    returnValueForMissingStub: null,
  );

  @override
  void restoreState(_i22.RestorationBucket? oldBucket, bool? initialRestore) =>
      super.noSuchMethod(
        Invocation.method(#restoreState, [oldBucket, initialRestore]),
        returnValueForMissingStub: null,
      );

  @override
  void didToggleBucket(_i22.RestorationBucket? oldBucket) => super.noSuchMethod(
    Invocation.method(#didToggleBucket, [oldBucket]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeDependencies() => super.noSuchMethod(
    Invocation.method(#didChangeDependencies, []),
    returnValueForMissingStub: null,
  );

  @override
  void didUpdateWidget(_i6.StatefulWidget? oldWidget) => super.noSuchMethod(
    Invocation.method(#didUpdateWidget, [oldWidget]),
    returnValueForMissingStub: null,
  );

  @override
  void deactivate() => super.noSuchMethod(
    Invocation.method(#deactivate, []),
    returnValueForMissingStub: null,
  );

  @override
  void activate() => super.noSuchMethod(
    Invocation.method(#activate, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i21.Future<T?> pushNamed<T extends Object?>(
    String? routeName, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushNamed, [routeName], {#arguments: arguments}),
            returnValue: _i21.Future<T?>.value(),
            returnValueForMissingStub: _i21.Future<T?>.value(),
          )
          as _i21.Future<T?>);

  @override
  String restorablePushNamed<T extends Object?>(
    String? routeName, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #restorablePushNamed,
              [routeName],
              {#arguments: arguments},
            ),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushNamed,
                [routeName],
                {#arguments: arguments},
              ),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushNamed,
                [routeName],
                {#arguments: arguments},
              ),
            ),
          )
          as String);

  @override
  _i21.Future<T?> pushReplacementNamed<T extends Object?, TO extends Object?>(
    String? routeName, {
    TO? result,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacementNamed,
              [routeName],
              {#result: result, #arguments: arguments},
            ),
            returnValue: _i21.Future<T?>.value(),
            returnValueForMissingStub: _i21.Future<T?>.value(),
          )
          as _i21.Future<T?>);

  @override
  String restorablePushReplacementNamed<T extends Object?, TO extends Object?>(
    String? routeName, {
    TO? result,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #restorablePushReplacementNamed,
              [routeName],
              {#result: result, #arguments: arguments},
            ),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushReplacementNamed,
                [routeName],
                {#result: result, #arguments: arguments},
              ),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushReplacementNamed,
                [routeName],
                {#result: result, #arguments: arguments},
              ),
            ),
          )
          as String);

  @override
  _i21.Future<T?> popAndPushNamed<T extends Object?, TO extends Object?>(
    String? routeName, {
    TO? result,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #popAndPushNamed,
              [routeName],
              {#result: result, #arguments: arguments},
            ),
            returnValue: _i21.Future<T?>.value(),
            returnValueForMissingStub: _i21.Future<T?>.value(),
          )
          as _i21.Future<T?>);

  @override
  String restorablePopAndPushNamed<T extends Object?, TO extends Object?>(
    String? routeName, {
    TO? result,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #restorablePopAndPushNamed,
              [routeName],
              {#result: result, #arguments: arguments},
            ),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePopAndPushNamed,
                [routeName],
                {#result: result, #arguments: arguments},
              ),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePopAndPushNamed,
                [routeName],
                {#result: result, #arguments: arguments},
              ),
            ),
          )
          as String);

  @override
  _i21.Future<T?> pushNamedAndRemoveUntil<T extends Object?>(
    String? newRouteName,
    _i5.RoutePredicate? predicate, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamedAndRemoveUntil,
              [newRouteName, predicate],
              {#arguments: arguments},
            ),
            returnValue: _i21.Future<T?>.value(),
            returnValueForMissingStub: _i21.Future<T?>.value(),
          )
          as _i21.Future<T?>);

  @override
  String restorablePushNamedAndRemoveUntil<T extends Object?>(
    String? newRouteName,
    _i5.RoutePredicate? predicate, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #restorablePushNamedAndRemoveUntil,
              [newRouteName, predicate],
              {#arguments: arguments},
            ),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushNamedAndRemoveUntil,
                [newRouteName, predicate],
                {#arguments: arguments},
              ),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushNamedAndRemoveUntil,
                [newRouteName, predicate],
                {#arguments: arguments},
              ),
            ),
          )
          as String);

  @override
  _i21.Future<T?> push<T extends Object?>(_i5.Route<T>? route) =>
      (super.noSuchMethod(
            Invocation.method(#push, [route]),
            returnValue: _i21.Future<T?>.value(),
            returnValueForMissingStub: _i21.Future<T?>.value(),
          )
          as _i21.Future<T?>);

  @override
  String restorablePush<T extends Object?>(
    _i5.RestorableRouteBuilder<T>? routeBuilder, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #restorablePush,
              [routeBuilder],
              {#arguments: arguments},
            ),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePush,
                [routeBuilder],
                {#arguments: arguments},
              ),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePush,
                [routeBuilder],
                {#arguments: arguments},
              ),
            ),
          )
          as String);

  @override
  _i21.Future<T?> pushReplacement<T extends Object?, TO extends Object?>(
    _i5.Route<T>? newRoute, {
    TO? result,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushReplacement, [newRoute], {#result: result}),
            returnValue: _i21.Future<T?>.value(),
            returnValueForMissingStub: _i21.Future<T?>.value(),
          )
          as _i21.Future<T?>);

  @override
  String restorablePushReplacement<T extends Object?, TO extends Object?>(
    _i5.RestorableRouteBuilder<T>? routeBuilder, {
    TO? result,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #restorablePushReplacement,
              [routeBuilder],
              {#result: result, #arguments: arguments},
            ),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushReplacement,
                [routeBuilder],
                {#result: result, #arguments: arguments},
              ),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushReplacement,
                [routeBuilder],
                {#result: result, #arguments: arguments},
              ),
            ),
          )
          as String);

  @override
  _i21.Future<T?> pushAndRemoveUntil<T extends Object?>(
    _i5.Route<T>? newRoute,
    _i5.RoutePredicate? predicate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#pushAndRemoveUntil, [newRoute, predicate]),
            returnValue: _i21.Future<T?>.value(),
            returnValueForMissingStub: _i21.Future<T?>.value(),
          )
          as _i21.Future<T?>);

  @override
  String restorablePushAndRemoveUntil<T extends Object?>(
    _i5.RestorableRouteBuilder<T>? newRouteBuilder,
    _i5.RoutePredicate? predicate, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #restorablePushAndRemoveUntil,
              [newRouteBuilder, predicate],
              {#arguments: arguments},
            ),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushAndRemoveUntil,
                [newRouteBuilder, predicate],
                {#arguments: arguments},
              ),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(
                #restorablePushAndRemoveUntil,
                [newRouteBuilder, predicate],
                {#arguments: arguments},
              ),
            ),
          )
          as String);

  @override
  void replace<T extends Object?>({
    required _i5.Route<dynamic>? oldRoute,
    required _i5.Route<T>? newRoute,
  }) => super.noSuchMethod(
    Invocation.method(#replace, [], {#oldRoute: oldRoute, #newRoute: newRoute}),
    returnValueForMissingStub: null,
  );

  @override
  String restorableReplace<T extends Object?>({
    required _i5.Route<dynamic>? oldRoute,
    required _i5.RestorableRouteBuilder<T>? newRouteBuilder,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restorableReplace, [], {
              #oldRoute: oldRoute,
              #newRouteBuilder: newRouteBuilder,
              #arguments: arguments,
            }),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(#restorableReplace, [], {
                #oldRoute: oldRoute,
                #newRouteBuilder: newRouteBuilder,
                #arguments: arguments,
              }),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(#restorableReplace, [], {
                #oldRoute: oldRoute,
                #newRouteBuilder: newRouteBuilder,
                #arguments: arguments,
              }),
            ),
          )
          as String);

  @override
  void replaceRouteBelow<T extends Object?>({
    required _i5.Route<dynamic>? anchorRoute,
    required _i5.Route<T>? newRoute,
  }) => super.noSuchMethod(
    Invocation.method(#replaceRouteBelow, [], {
      #anchorRoute: anchorRoute,
      #newRoute: newRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  String restorableReplaceRouteBelow<T extends Object?>({
    required _i5.Route<dynamic>? anchorRoute,
    required _i5.RestorableRouteBuilder<T>? newRouteBuilder,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restorableReplaceRouteBelow, [], {
              #anchorRoute: anchorRoute,
              #newRouteBuilder: newRouteBuilder,
              #arguments: arguments,
            }),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(#restorableReplaceRouteBelow, [], {
                #anchorRoute: anchorRoute,
                #newRouteBuilder: newRouteBuilder,
                #arguments: arguments,
              }),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(#restorableReplaceRouteBelow, [], {
                #anchorRoute: anchorRoute,
                #newRouteBuilder: newRouteBuilder,
                #arguments: arguments,
              }),
            ),
          )
          as String);

  @override
  bool canPop() =>
      (super.noSuchMethod(
            Invocation.method(#canPop, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i21.Future<bool> maybePop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#maybePop, [result]),
            returnValue: _i21.Future<bool>.value(false),
            returnValueForMissingStub: _i21.Future<bool>.value(false),
          )
          as _i21.Future<bool>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void popUntil(_i5.RoutePredicate? predicate) => super.noSuchMethod(
    Invocation.method(#popUntil, [predicate]),
    returnValueForMissingStub: null,
  );

  @override
  void popUntilWithResult<T extends Object?>(
    _i5.RoutePredicate? predicate,
    T? result,
  ) => super.noSuchMethod(
    Invocation.method(#popUntilWithResult, [predicate, result]),
    returnValueForMissingStub: null,
  );

  @override
  void removeRoute<T extends Object?>(_i5.Route<T>? route, [T? result]) =>
      super.noSuchMethod(
        Invocation.method(#removeRoute, [route, result]),
        returnValueForMissingStub: null,
      );

  @override
  void removeRouteBelow<T extends Object?>(
    _i5.Route<T>? anchorRoute, [
    T? result,
  ]) => super.noSuchMethod(
    Invocation.method(#removeRouteBelow, [anchorRoute, result]),
    returnValueForMissingStub: null,
  );

  @override
  void finalizeRoute(_i5.Route<dynamic>? route) => super.noSuchMethod(
    Invocation.method(#finalizeRoute, [route]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture() => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Widget build(_i6.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#build, [context]),
            returnValue: _FakeWidget_5(
              this,
              Invocation.method(#build, [context]),
            ),
            returnValueForMissingStub: _FakeWidget_5(
              this,
              Invocation.method(#build, [context]),
            ),
          )
          as _i6.Widget);

  @override
  void reassemble() => super.noSuchMethod(
    Invocation.method(#reassemble, []),
    returnValueForMissingStub: null,
  );

  @override
  void setState(_i24.VoidCallback? fn) => super.noSuchMethod(
    Invocation.method(#setState, [fn]),
    returnValueForMissingStub: null,
  );

  @override
  void debugFillProperties(_i4.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(#debugFillProperties, [properties]),
        returnValueForMissingStub: null,
      );

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();

  @override
  String toStringShort() =>
      (super.noSuchMethod(
            Invocation.method(#toStringShort, []),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(#toStringShort, []),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(#toStringShort, []),
            ),
          )
          as String);

  @override
  _i4.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i4.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toDiagnosticsNode, [], {
              #name: name,
              #style: style,
            }),
            returnValue: _FakeDiagnosticsNode_6(
              this,
              Invocation.method(#toDiagnosticsNode, [], {
                #name: name,
                #style: style,
              }),
            ),
            returnValueForMissingStub: _FakeDiagnosticsNode_6(
              this,
              Invocation.method(#toDiagnosticsNode, [], {
                #name: name,
                #style: style,
              }),
            ),
          )
          as _i4.DiagnosticsNode);

  @override
  _i7.Ticker createTicker(_i7.TickerCallback? onTick) =>
      (super.noSuchMethod(
            Invocation.method(#createTicker, [onTick]),
            returnValue: _FakeTicker_7(
              this,
              Invocation.method(#createTicker, [onTick]),
            ),
            returnValueForMissingStub: _FakeTicker_7(
              this,
              Invocation.method(#createTicker, [onTick]),
            ),
          )
          as _i7.Ticker);

  @override
  void registerForRestoration(
    _i25.RestorableProperty<Object?>? property,
    String? restorationId,
  ) => super.noSuchMethod(
    Invocation.method(#registerForRestoration, [property, restorationId]),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterFromRestoration(_i25.RestorableProperty<Object?>? property) =>
      super.noSuchMethod(
        Invocation.method(#unregisterFromRestoration, [property]),
        returnValueForMissingStub: null,
      );

  @override
  void didUpdateRestorationId() => super.noSuchMethod(
    Invocation.method(#didUpdateRestorationId, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ScaffoldMessengerState].
///
/// See the documentation for Mockito's code generation for more information.
class MockScaffoldMessengerState extends _i1.Mock
    implements _i8.ScaffoldMessengerState {
  @override
  _i8.ScaffoldMessenger get widget =>
      (super.noSuchMethod(
            Invocation.getter(#widget),
            returnValue: _FakeScaffoldMessenger_8(
              this,
              Invocation.getter(#widget),
            ),
            returnValueForMissingStub: _FakeScaffoldMessenger_8(
              this,
              Invocation.getter(#widget),
            ),
          )
          as _i8.ScaffoldMessenger);

  @override
  _i6.BuildContext get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _FakeBuildContext_4(this, Invocation.getter(#context)),
            returnValueForMissingStub: _FakeBuildContext_4(
              this,
              Invocation.getter(#context),
            ),
          )
          as _i6.BuildContext);

  @override
  bool get mounted =>
      (super.noSuchMethod(
            Invocation.getter(#mounted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void didChangeDependencies() => super.noSuchMethod(
    Invocation.method(#didChangeDependencies, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.ScaffoldFeatureController<_i26.SnackBar, _i26.SnackBarClosedReason>
  showSnackBar(
    _i26.SnackBar? snackBar, {
    _i27.AnimationStyle? snackBarAnimationStyle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #showSnackBar,
              [snackBar],
              {#snackBarAnimationStyle: snackBarAnimationStyle},
            ),
            returnValue:
                _FakeScaffoldFeatureController_9<
                  _i26.SnackBar,
                  _i26.SnackBarClosedReason
                >(
                  this,
                  Invocation.method(
                    #showSnackBar,
                    [snackBar],
                    {#snackBarAnimationStyle: snackBarAnimationStyle},
                  ),
                ),
            returnValueForMissingStub:
                _FakeScaffoldFeatureController_9<
                  _i26.SnackBar,
                  _i26.SnackBarClosedReason
                >(
                  this,
                  Invocation.method(
                    #showSnackBar,
                    [snackBar],
                    {#snackBarAnimationStyle: snackBarAnimationStyle},
                  ),
                ),
          )
          as _i8.ScaffoldFeatureController<
            _i26.SnackBar,
            _i26.SnackBarClosedReason
          >);

  @override
  void removeCurrentSnackBar({
    _i26.SnackBarClosedReason? reason = _i26.SnackBarClosedReason.remove,
  }) => super.noSuchMethod(
    Invocation.method(#removeCurrentSnackBar, [], {#reason: reason}),
    returnValueForMissingStub: null,
  );

  @override
  void hideCurrentSnackBar({
    _i26.SnackBarClosedReason? reason = _i26.SnackBarClosedReason.hide,
  }) => super.noSuchMethod(
    Invocation.method(#hideCurrentSnackBar, [], {#reason: reason}),
    returnValueForMissingStub: null,
  );

  @override
  void clearSnackBars() => super.noSuchMethod(
    Invocation.method(#clearSnackBars, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.ScaffoldFeatureController<
    _i28.MaterialBanner,
    _i28.MaterialBannerClosedReason
  >
  showMaterialBanner(_i28.MaterialBanner? materialBanner) =>
      (super.noSuchMethod(
            Invocation.method(#showMaterialBanner, [materialBanner]),
            returnValue:
                _FakeScaffoldFeatureController_9<
                  _i28.MaterialBanner,
                  _i28.MaterialBannerClosedReason
                >(
                  this,
                  Invocation.method(#showMaterialBanner, [materialBanner]),
                ),
            returnValueForMissingStub:
                _FakeScaffoldFeatureController_9<
                  _i28.MaterialBanner,
                  _i28.MaterialBannerClosedReason
                >(
                  this,
                  Invocation.method(#showMaterialBanner, [materialBanner]),
                ),
          )
          as _i8.ScaffoldFeatureController<
            _i28.MaterialBanner,
            _i28.MaterialBannerClosedReason
          >);

  @override
  void removeCurrentMaterialBanner({
    _i28.MaterialBannerClosedReason? reason =
        _i28.MaterialBannerClosedReason.remove,
  }) => super.noSuchMethod(
    Invocation.method(#removeCurrentMaterialBanner, [], {#reason: reason}),
    returnValueForMissingStub: null,
  );

  @override
  void hideCurrentMaterialBanner({
    _i28.MaterialBannerClosedReason? reason =
        _i28.MaterialBannerClosedReason.hide,
  }) => super.noSuchMethod(
    Invocation.method(#hideCurrentMaterialBanner, [], {#reason: reason}),
    returnValueForMissingStub: null,
  );

  @override
  void clearMaterialBanners() => super.noSuchMethod(
    Invocation.method(#clearMaterialBanners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Widget build(_i6.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#build, [context]),
            returnValue: _FakeWidget_5(
              this,
              Invocation.method(#build, [context]),
            ),
            returnValueForMissingStub: _FakeWidget_5(
              this,
              Invocation.method(#build, [context]),
            ),
          )
          as _i6.Widget);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void initState() => super.noSuchMethod(
    Invocation.method(#initState, []),
    returnValueForMissingStub: null,
  );

  @override
  void didUpdateWidget(_i8.ScaffoldMessenger? oldWidget) => super.noSuchMethod(
    Invocation.method(#didUpdateWidget, [oldWidget]),
    returnValueForMissingStub: null,
  );

  @override
  void reassemble() => super.noSuchMethod(
    Invocation.method(#reassemble, []),
    returnValueForMissingStub: null,
  );

  @override
  void setState(_i24.VoidCallback? fn) => super.noSuchMethod(
    Invocation.method(#setState, [fn]),
    returnValueForMissingStub: null,
  );

  @override
  void deactivate() => super.noSuchMethod(
    Invocation.method(#deactivate, []),
    returnValueForMissingStub: null,
  );

  @override
  void activate() => super.noSuchMethod(
    Invocation.method(#activate, []),
    returnValueForMissingStub: null,
  );

  @override
  void debugFillProperties(_i4.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(#debugFillProperties, [properties]),
        returnValueForMissingStub: null,
      );

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();

  @override
  String toStringShort() =>
      (super.noSuchMethod(
            Invocation.method(#toStringShort, []),
            returnValue: _i23.dummyValue<String>(
              this,
              Invocation.method(#toStringShort, []),
            ),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.method(#toStringShort, []),
            ),
          )
          as String);

  @override
  _i4.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i4.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toDiagnosticsNode, [], {
              #name: name,
              #style: style,
            }),
            returnValue: _FakeDiagnosticsNode_6(
              this,
              Invocation.method(#toDiagnosticsNode, [], {
                #name: name,
                #style: style,
              }),
            ),
            returnValueForMissingStub: _FakeDiagnosticsNode_6(
              this,
              Invocation.method(#toDiagnosticsNode, [], {
                #name: name,
                #style: style,
              }),
            ),
          )
          as _i4.DiagnosticsNode);

  @override
  _i7.Ticker createTicker(_i7.TickerCallback? onTick) =>
      (super.noSuchMethod(
            Invocation.method(#createTicker, [onTick]),
            returnValue: _FakeTicker_7(
              this,
              Invocation.method(#createTicker, [onTick]),
            ),
            returnValueForMissingStub: _FakeTicker_7(
              this,
              Invocation.method(#createTicker, [onTick]),
            ),
          )
          as _i7.Ticker);
}

/// A class which mocks [OrignaBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrignaBase extends _i1.Mock implements _i29.OrignaBase {
  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i23.dummyValue<String>(this, Invocation.getter(#url)),
            returnValueForMissingStub: _i23.dummyValue<String>(
              this,
              Invocation.getter(#url),
            ),
          )
          as String);

  @override
  _i9.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_10(this, Invocation.getter(#httpClient)),
            returnValueForMissingStub: _FakeClient_10(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i9.Client);

  @override
  _i10.OrignaBaseAuth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeOrignaBaseAuth_11(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeOrignaBaseAuth_11(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i10.OrignaBaseAuth);

  @override
  _i11.OrignaBaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeOrignaBaseStorage_12(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeOrignaBaseStorage_12(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i11.OrignaBaseStorage);

  @override
  _i12.OfflineCache get offline =>
      (super.noSuchMethod(
            Invocation.getter(#offline),
            returnValue: _FakeOfflineCache_13(
              this,
              Invocation.getter(#offline),
            ),
            returnValueForMissingStub: _FakeOfflineCache_13(
              this,
              Invocation.getter(#offline),
            ),
          )
          as _i12.OfflineCache);

  @override
  _i13.OrignaBaseConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeOrignaBaseConfig_14(
              this,
              Invocation.getter(#config),
            ),
            returnValueForMissingStub: _FakeOrignaBaseConfig_14(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i13.OrignaBaseConfig);

  @override
  _i14.OrignaBasePresence get presence =>
      (super.noSuchMethod(
            Invocation.getter(#presence),
            returnValue: _FakeOrignaBasePresence_15(
              this,
              Invocation.getter(#presence),
            ),
            returnValueForMissingStub: _FakeOrignaBasePresence_15(
              this,
              Invocation.getter(#presence),
            ),
          )
          as _i14.OrignaBasePresence);

  @override
  _i15.OrignaBaseLinks get links =>
      (super.noSuchMethod(
            Invocation.getter(#links),
            returnValue: _FakeOrignaBaseLinks_16(
              this,
              Invocation.getter(#links),
            ),
            returnValueForMissingStub: _FakeOrignaBaseLinks_16(
              this,
              Invocation.getter(#links),
            ),
          )
          as _i15.OrignaBaseLinks);

  @override
  _i16.OrignaBasePush get push =>
      (super.noSuchMethod(
            Invocation.getter(#push),
            returnValue: _FakeOrignaBasePush_17(this, Invocation.getter(#push)),
            returnValueForMissingStub: _FakeOrignaBasePush_17(
              this,
              Invocation.getter(#push),
            ),
          )
          as _i16.OrignaBasePush);

  @override
  _i17.OrignaBaseMetrics get metrics =>
      (super.noSuchMethod(
            Invocation.getter(#metrics),
            returnValue: _FakeOrignaBaseMetrics_18(
              this,
              Invocation.getter(#metrics),
            ),
            returnValueForMissingStub: _FakeOrignaBaseMetrics_18(
              this,
              Invocation.getter(#metrics),
            ),
          )
          as _i17.OrignaBaseMetrics);

  @override
  _i18.VectorSearch get vectorSearch =>
      (super.noSuchMethod(
            Invocation.getter(#vectorSearch),
            returnValue: _FakeVectorSearch_19(
              this,
              Invocation.getter(#vectorSearch),
            ),
            returnValueForMissingStub: _FakeVectorSearch_19(
              this,
              Invocation.getter(#vectorSearch),
            ),
          )
          as _i18.VectorSearch);

  @override
  set auth(_i10.OrignaBaseAuth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i11.OrignaBaseStorage? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set offline(_i12.OfflineCache? value) => super.noSuchMethod(
    Invocation.setter(#offline, value),
    returnValueForMissingStub: null,
  );

  @override
  set config(_i13.OrignaBaseConfig? value) => super.noSuchMethod(
    Invocation.setter(#config, value),
    returnValueForMissingStub: null,
  );

  @override
  set presence(_i14.OrignaBasePresence? value) => super.noSuchMethod(
    Invocation.setter(#presence, value),
    returnValueForMissingStub: null,
  );

  @override
  set links(_i15.OrignaBaseLinks? value) => super.noSuchMethod(
    Invocation.setter(#links, value),
    returnValueForMissingStub: null,
  );

  @override
  set push(_i16.OrignaBasePush? value) => super.noSuchMethod(
    Invocation.setter(#push, value),
    returnValueForMissingStub: null,
  );

  @override
  set metrics(_i17.OrignaBaseMetrics? value) => super.noSuchMethod(
    Invocation.setter(#metrics, value),
    returnValueForMissingStub: null,
  );

  @override
  set vectorSearch(_i18.VectorSearch? value) => super.noSuchMethod(
    Invocation.setter(#vectorSearch, value),
    returnValueForMissingStub: null,
  );

  @override
  _i19.CollectionRef collection(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [name]),
            returnValue: _FakeCollectionRef_20(
              this,
              Invocation.method(#collection, [name]),
            ),
            returnValueForMissingStub: _FakeCollectionRef_20(
              this,
              Invocation.method(#collection, [name]),
            ),
          )
          as _i19.CollectionRef);

  @override
  _i20.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_21(
              this,
              Invocation.method(#batch, []),
            ),
            returnValueForMissingStub: _FakeWriteBatch_21(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i20.WriteBatch);

  @override
  _i21.Future<Map<String, dynamic>> graphql(
    String? query, {
    Map<String, dynamic>? variables,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#graphql, [query], {#variables: variables}),
            returnValue: _i21.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i21.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i21.Future<Map<String, dynamic>>);

  @override
  _i21.Future<Map<String, dynamic>> request(
    String? method,
    String? path, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [method, path],
              {#body: body, #headers: headers},
            ),
            returnValue: _i21.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i21.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i21.Future<Map<String, dynamic>>);

  @override
  _i21.Future<Map<String, dynamic>> search(
    String? index,
    String? query, {
    int? limit,
    int? offset,
    String? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [index, query],
              {#limit: limit, #offset: offset, #filter: filter},
            ),
            returnValue: _i21.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i21.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i21.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OrignaBasePush].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrignaBasePush extends _i1.Mock implements _i16.OrignaBasePush {
  @override
  _i21.Future<void> registerToken({
    required String? userId,
    required String? token,
    required String? platform,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerToken, [], {
              #userId: userId,
              #token: token,
              #platform: platform,
            }),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);

  @override
  _i21.Future<void> unregisterToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#unregisterToken, [token]),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);

  @override
  _i21.Future<_i16.PushResult> sendToUser(
    String? userId, {
    required String? title,
    required String? body,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendToUser,
              [userId],
              {#title: title, #body: body, #data: data},
            ),
            returnValue: _i21.Future<_i16.PushResult>.value(
              _FakePushResult_22(
                this,
                Invocation.method(
                  #sendToUser,
                  [userId],
                  {#title: title, #body: body, #data: data},
                ),
              ),
            ),
            returnValueForMissingStub: _i21.Future<_i16.PushResult>.value(
              _FakePushResult_22(
                this,
                Invocation.method(
                  #sendToUser,
                  [userId],
                  {#title: title, #body: body, #data: data},
                ),
              ),
            ),
          )
          as _i21.Future<_i16.PushResult>);

  @override
  _i21.Future<_i16.PushResult> sendToToken(
    String? token, {
    required String? title,
    required String? body,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendToToken,
              [token],
              {#title: title, #body: body, #data: data},
            ),
            returnValue: _i21.Future<_i16.PushResult>.value(
              _FakePushResult_22(
                this,
                Invocation.method(
                  #sendToToken,
                  [token],
                  {#title: title, #body: body, #data: data},
                ),
              ),
            ),
            returnValueForMissingStub: _i21.Future<_i16.PushResult>.value(
              _FakePushResult_22(
                this,
                Invocation.method(
                  #sendToToken,
                  [token],
                  {#title: title, #body: body, #data: data},
                ),
              ),
            ),
          )
          as _i21.Future<_i16.PushResult>);

  @override
  _i21.Future<_i16.PushResult> sendToTopic(
    String? topic, {
    required String? title,
    required String? body,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendToTopic,
              [topic],
              {#title: title, #body: body, #data: data},
            ),
            returnValue: _i21.Future<_i16.PushResult>.value(
              _FakePushResult_22(
                this,
                Invocation.method(
                  #sendToTopic,
                  [topic],
                  {#title: title, #body: body, #data: data},
                ),
              ),
            ),
            returnValueForMissingStub: _i21.Future<_i16.PushResult>.value(
              _FakePushResult_22(
                this,
                Invocation.method(
                  #sendToTopic,
                  [topic],
                  {#title: title, #body: body, #data: data},
                ),
              ),
            ),
          )
          as _i21.Future<_i16.PushResult>);

  @override
  _i21.Future<void> subscribeToTopic(String? token, String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [token, topic]),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);

  @override
  _i21.Future<void> unsubscribeFromTopic(String? token, String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [token, topic]),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);
}
