// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/unit/orignabase_chat_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:orignabase/src/auth.dart' as _i3;
import 'package:orignabase/src/batch.dart' as _i14;
import 'package:orignabase/src/client.dart' as _i15;
import 'package:orignabase/src/collection.dart' as _i13;
import 'package:orignabase/src/config.dart' as _i6;
import 'package:orignabase/src/document.dart' as _i17;
import 'package:orignabase/src/links.dart' as _i8;
import 'package:orignabase/src/metrics.dart' as _i10;
import 'package:orignabase/src/offline.dart' as _i5;
import 'package:orignabase/src/presence.dart' as _i7;
import 'package:orignabase/src/push.dart' as _i9;
import 'package:orignabase/src/query.dart' as _i18;
import 'package:orignabase/src/realtime.dart' as _i12;
import 'package:orignabase/src/storage.dart' as _i4;
import 'package:orignabase/src/subcollection.dart' as _i16;
import 'package:orignabase/src/vector.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseAuth_1 extends _i1.SmartFake
    implements _i3.OrignaBaseAuth {
  _FakeOrignaBaseAuth_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseStorage_2 extends _i1.SmartFake
    implements _i4.OrignaBaseStorage {
  _FakeOrignaBaseStorage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfflineCache_3 extends _i1.SmartFake implements _i5.OfflineCache {
  _FakeOfflineCache_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseConfig_4 extends _i1.SmartFake
    implements _i6.OrignaBaseConfig {
  _FakeOrignaBaseConfig_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePresence_5 extends _i1.SmartFake
    implements _i7.OrignaBasePresence {
  _FakeOrignaBasePresence_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseLinks_6 extends _i1.SmartFake
    implements _i8.OrignaBaseLinks {
  _FakeOrignaBaseLinks_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePush_7 extends _i1.SmartFake
    implements _i9.OrignaBasePush {
  _FakeOrignaBasePush_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseMetrics_8 extends _i1.SmartFake
    implements _i10.OrignaBaseMetrics {
  _FakeOrignaBaseMetrics_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVectorSearch_9 extends _i1.SmartFake implements _i11.VectorSearch {
  _FakeVectorSearch_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_10 extends _i1.SmartFake
    implements _i12.RealtimeClient {
  _FakeRealtimeClient_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionRef_11 extends _i1.SmartFake
    implements _i13.CollectionRef {
  _FakeCollectionRef_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_12 extends _i1.SmartFake implements _i14.WriteBatch {
  _FakeWriteBatch_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthState_13 extends _i1.SmartFake implements _i3.AuthState {
  _FakeAuthState_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaSetupResult_14 extends _i1.SmartFake
    implements _i3.MfaSetupResult {
  _FakeMfaSetupResult_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBase_15 extends _i1.SmartFake implements _i15.OrignaBase {
  _FakeOrignaBase_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentRef_16 extends _i1.SmartFake implements _i13.DocumentRef {
  _FakeDocumentRef_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubcollectionRef_17 extends _i1.SmartFake
    implements _i16.SubcollectionRef {
  _FakeSubcollectionRef_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocument_18 extends _i1.SmartFake implements _i17.Document {
  _FakeDocument_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_19 extends _i1.SmartFake implements _i18.Query {
  _FakeQuery_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_20 extends _i1.SmartFake
    implements _i17.QuerySnapshot {
  _FakeQuerySnapshot_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrignaBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrignaBase extends _i1.Mock implements _i15.OrignaBase {
  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i19.dummyValue<String>(this, Invocation.getter(#url)),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#url),
            ),
          )
          as String);

  @override
  _i2.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_0(this, Invocation.getter(#httpClient)),
            returnValueForMissingStub: _FakeClient_0(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i2.Client);

  @override
  _i3.OrignaBaseAuth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeOrignaBaseAuth_1(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeOrignaBaseAuth_1(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i3.OrignaBaseAuth);

  @override
  _i4.OrignaBaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeOrignaBaseStorage_2(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeOrignaBaseStorage_2(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i4.OrignaBaseStorage);

  @override
  _i5.OfflineCache get offline =>
      (super.noSuchMethod(
            Invocation.getter(#offline),
            returnValue: _FakeOfflineCache_3(this, Invocation.getter(#offline)),
            returnValueForMissingStub: _FakeOfflineCache_3(
              this,
              Invocation.getter(#offline),
            ),
          )
          as _i5.OfflineCache);

  @override
  _i6.OrignaBaseConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeOrignaBaseConfig_4(
              this,
              Invocation.getter(#config),
            ),
            returnValueForMissingStub: _FakeOrignaBaseConfig_4(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i6.OrignaBaseConfig);

  @override
  _i7.OrignaBasePresence get presence =>
      (super.noSuchMethod(
            Invocation.getter(#presence),
            returnValue: _FakeOrignaBasePresence_5(
              this,
              Invocation.getter(#presence),
            ),
            returnValueForMissingStub: _FakeOrignaBasePresence_5(
              this,
              Invocation.getter(#presence),
            ),
          )
          as _i7.OrignaBasePresence);

  @override
  _i8.OrignaBaseLinks get links =>
      (super.noSuchMethod(
            Invocation.getter(#links),
            returnValue: _FakeOrignaBaseLinks_6(
              this,
              Invocation.getter(#links),
            ),
            returnValueForMissingStub: _FakeOrignaBaseLinks_6(
              this,
              Invocation.getter(#links),
            ),
          )
          as _i8.OrignaBaseLinks);

  @override
  _i9.OrignaBasePush get push =>
      (super.noSuchMethod(
            Invocation.getter(#push),
            returnValue: _FakeOrignaBasePush_7(this, Invocation.getter(#push)),
            returnValueForMissingStub: _FakeOrignaBasePush_7(
              this,
              Invocation.getter(#push),
            ),
          )
          as _i9.OrignaBasePush);

  @override
  _i10.OrignaBaseMetrics get metrics =>
      (super.noSuchMethod(
            Invocation.getter(#metrics),
            returnValue: _FakeOrignaBaseMetrics_8(
              this,
              Invocation.getter(#metrics),
            ),
            returnValueForMissingStub: _FakeOrignaBaseMetrics_8(
              this,
              Invocation.getter(#metrics),
            ),
          )
          as _i10.OrignaBaseMetrics);

  @override
  _i11.VectorSearch get vectorSearch =>
      (super.noSuchMethod(
            Invocation.getter(#vectorSearch),
            returnValue: _FakeVectorSearch_9(
              this,
              Invocation.getter(#vectorSearch),
            ),
            returnValueForMissingStub: _FakeVectorSearch_9(
              this,
              Invocation.getter(#vectorSearch),
            ),
          )
          as _i11.VectorSearch);

  @override
  _i12.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_10(
              this,
              Invocation.getter(#realtime),
            ),
            returnValueForMissingStub: _FakeRealtimeClient_10(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i12.RealtimeClient);

  @override
  set auth(_i3.OrignaBaseAuth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i4.OrignaBaseStorage? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set offline(_i5.OfflineCache? value) => super.noSuchMethod(
    Invocation.setter(#offline, value),
    returnValueForMissingStub: null,
  );

  @override
  set config(_i6.OrignaBaseConfig? value) => super.noSuchMethod(
    Invocation.setter(#config, value),
    returnValueForMissingStub: null,
  );

  @override
  set presence(_i7.OrignaBasePresence? value) => super.noSuchMethod(
    Invocation.setter(#presence, value),
    returnValueForMissingStub: null,
  );

  @override
  set links(_i8.OrignaBaseLinks? value) => super.noSuchMethod(
    Invocation.setter(#links, value),
    returnValueForMissingStub: null,
  );

  @override
  set push(_i9.OrignaBasePush? value) => super.noSuchMethod(
    Invocation.setter(#push, value),
    returnValueForMissingStub: null,
  );

  @override
  set metrics(_i10.OrignaBaseMetrics? value) => super.noSuchMethod(
    Invocation.setter(#metrics, value),
    returnValueForMissingStub: null,
  );

  @override
  set vectorSearch(_i11.VectorSearch? value) => super.noSuchMethod(
    Invocation.setter(#vectorSearch, value),
    returnValueForMissingStub: null,
  );

  @override
  _i13.CollectionRef collection(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [name]),
            returnValue: _FakeCollectionRef_11(
              this,
              Invocation.method(#collection, [name]),
            ),
            returnValueForMissingStub: _FakeCollectionRef_11(
              this,
              Invocation.method(#collection, [name]),
            ),
          )
          as _i13.CollectionRef);

  @override
  _i14.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_12(
              this,
              Invocation.method(#batch, []),
            ),
            returnValueForMissingStub: _FakeWriteBatch_12(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i14.WriteBatch);

  @override
  _i20.Future<Map<String, dynamic>> graphql(
    String? query, {
    Map<String, dynamic>? variables,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#graphql, [query], {#variables: variables}),
            returnValue: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i20.Future<Map<String, dynamic>>);

  @override
  _i20.Future<Map<String, dynamic>> request(
    String? method,
    String? path, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [method, path],
              {#body: body, #headers: headers},
            ),
            returnValue: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i20.Future<Map<String, dynamic>>);

  @override
  _i20.Future<Map<String, dynamic>> search(
    String? index,
    String? query, {
    int? limit,
    int? offset,
    String? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [index, query],
              {#limit: limit, #offset: offset, #filter: filter},
            ),
            returnValue: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i20.Future<Map<String, dynamic>>);

  @override
  void closeRealtime() => super.noSuchMethod(
    Invocation.method(#closeRealtime, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OrignaBaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrignaBaseAuth extends _i1.Mock implements _i3.OrignaBaseAuth {
  @override
  _i20.Stream<_i3.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i20.Stream<_i3.AuthState>.empty(),
            returnValueForMissingStub: _i20.Stream<_i3.AuthState>.empty(),
          )
          as _i20.Stream<_i3.AuthState>);

  @override
  Map<String, dynamic> get currentClaims =>
      (super.noSuchMethod(
            Invocation.getter(#currentClaims),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<String> get currentRoles =>
      (super.noSuchMethod(
            Invocation.getter(#currentRoles),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get isEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isEmailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.AuthState get currentState =>
      (super.noSuchMethod(
            Invocation.getter(#currentState),
            returnValue: _FakeAuthState_13(
              this,
              Invocation.getter(#currentState),
            ),
            returnValueForMissingStub: _FakeAuthState_13(
              this,
              Invocation.getter(#currentState),
            ),
          )
          as _i3.AuthState);

  @override
  _i20.Future<_i3.AuthState> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#register, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#register, [email, password]),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<_i3.AuthState> signInWithEmail(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<_i3.AuthState> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(this, Invocation.method(#refreshToken, [])),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(this, Invocation.method(#refreshToken, [])),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<_i3.AuthState> signInWithGoogle(String? idToken) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, [idToken]),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#signInWithGoogle, [idToken]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#signInWithGoogle, [idToken]),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<_i3.AuthState> signInWithApple(
    String? authorizationCode, {
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #signInWithApple,
              [authorizationCode],
              {#displayName: displayName},
            ),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(
                  #signInWithApple,
                  [authorizationCode],
                  {#displayName: displayName},
                ),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(
                  #signInWithApple,
                  [authorizationCode],
                  {#displayName: displayName},
                ),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<_i3.AuthState> signInWithOidc(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOidc, [accessToken]),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#signInWithOidc, [accessToken]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#signInWithOidc, [accessToken]),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<void> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> resetPassword(String? token, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [token, newPassword]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i3.AuthState> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<_i3.AuthState> upgradeAnonymous(
    String? email,
    String? password, {
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upgradeAnonymous,
              [email, password],
              {#displayName: displayName},
            ),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(
                  #upgradeAnonymous,
                  [email, password],
                  {#displayName: displayName},
                ),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(
                  #upgradeAnonymous,
                  [email, password],
                  {#displayName: displayName},
                ),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<void> sendMagicLink(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendMagicLink, [email]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i3.AuthState> verifyMagicLink(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMagicLink, [token]),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#verifyMagicLink, [token]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#verifyMagicLink, [token]),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> verifyEmail(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [token]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i3.MfaSetupResult> setupMfa() =>
      (super.noSuchMethod(
            Invocation.method(#setupMfa, []),
            returnValue: _i20.Future<_i3.MfaSetupResult>.value(
              _FakeMfaSetupResult_14(this, Invocation.method(#setupMfa, [])),
            ),
            returnValueForMissingStub: _i20.Future<_i3.MfaSetupResult>.value(
              _FakeMfaSetupResult_14(this, Invocation.method(#setupMfa, [])),
            ),
          )
          as _i20.Future<_i3.MfaSetupResult>);

  @override
  _i20.Future<List<String>> verifyMfaSetup(String? totpCode) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMfaSetup, [totpCode]),
            returnValue: _i20.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i20.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i20.Future<List<String>>);

  @override
  _i20.Future<_i3.AuthState> verifyMfaChallenge(
    String? challengeToken,
    String? totpCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMfaChallenge, [challengeToken, totpCode]),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#verifyMfaChallenge, [
                  challengeToken,
                  totpCode,
                ]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#verifyMfaChallenge, [
                  challengeToken,
                  totpCode,
                ]),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<_i3.AuthState> useMfaRecoveryCode(
    String? challengeToken,
    String? recoveryCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#useMfaRecoveryCode, [
              challengeToken,
              recoveryCode,
            ]),
            returnValue: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#useMfaRecoveryCode, [
                  challengeToken,
                  recoveryCode,
                ]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i3.AuthState>.value(
              _FakeAuthState_13(
                this,
                Invocation.method(#useMfaRecoveryCode, [
                  challengeToken,
                  recoveryCode,
                ]),
              ),
            ),
          )
          as _i20.Future<_i3.AuthState>);

  @override
  _i20.Future<void> disableMfa(String? totpCode) =>
      (super.noSuchMethod(
            Invocation.method(#disableMfa, [totpCode]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<List<Map<String, dynamic>>> getLoginHistory({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLoginHistory, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i20.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i20.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i20.Future<List<Map<String, dynamic>>>);

  @override
  _i20.Future<List<Map<String, dynamic>>> getKnownDevices() =>
      (super.noSuchMethod(
            Invocation.method(#getKnownDevices, []),
            returnValue: _i20.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i20.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i20.Future<List<Map<String, dynamic>>>);

  @override
  _i20.Future<void> removeDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#removeDevice, [deviceId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<List<Map<String, dynamic>>> getSecurityAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#getSecurityAlerts, []),
            returnValue: _i20.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i20.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i20.Future<List<Map<String, dynamic>>>);

  @override
  _i20.Future<void> acknowledgeAlert(String? alertId) =>
      (super.noSuchMethod(
            Invocation.method(#acknowledgeAlert, [alertId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i3.AuthState restoreSession({
    required String? accessToken,
    String? refreshToken,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #email: email,
            }),
            returnValue: _FakeAuthState_13(
              this,
              Invocation.method(#restoreSession, [], {
                #accessToken: accessToken,
                #refreshToken: refreshToken,
                #email: email,
              }),
            ),
            returnValueForMissingStub: _FakeAuthState_13(
              this,
              Invocation.method(#restoreSession, [], {
                #accessToken: accessToken,
                #refreshToken: refreshToken,
                #email: email,
              }),
            ),
          )
          as _i3.AuthState);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CollectionRef].
///
/// See the documentation for Mockito's code generation for more information.
class MockCollectionRef extends _i1.Mock implements _i13.CollectionRef {
  @override
  _i15.OrignaBase get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeOrignaBase_15(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeOrignaBase_15(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i15.OrignaBase);

  @override
  String get collectionName =>
      (super.noSuchMethod(
            Invocation.getter(#collectionName),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
          )
          as String);

  @override
  _i13.DocumentRef doc(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [id]),
            returnValue: _FakeDocumentRef_16(
              this,
              Invocation.method(#doc, [id]),
            ),
            returnValueForMissingStub: _FakeDocumentRef_16(
              this,
              Invocation.method(#doc, [id]),
            ),
          )
          as _i13.DocumentRef);

  @override
  _i16.SubcollectionRef subcollection(String? docId, String? childCollection) =>
      (super.noSuchMethod(
            Invocation.method(#subcollection, [docId, childCollection]),
            returnValue: _FakeSubcollectionRef_17(
              this,
              Invocation.method(#subcollection, [docId, childCollection]),
            ),
            returnValueForMissingStub: _FakeSubcollectionRef_17(
              this,
              Invocation.method(#subcollection, [docId, childCollection]),
            ),
          )
          as _i16.SubcollectionRef);

  @override
  _i20.Stream<_i12.DocumentChange> snapshots() =>
      (super.noSuchMethod(
            Invocation.method(#snapshots, []),
            returnValue: _i20.Stream<_i12.DocumentChange>.empty(),
            returnValueForMissingStub: _i20.Stream<_i12.DocumentChange>.empty(),
          )
          as _i20.Stream<_i12.DocumentChange>);

  @override
  _i20.Future<_i17.Document> add(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#add, [data]),
            returnValue: _i20.Future<_i17.Document>.value(
              _FakeDocument_18(this, Invocation.method(#add, [data])),
            ),
            returnValueForMissingStub: _i20.Future<_i17.Document>.value(
              _FakeDocument_18(this, Invocation.method(#add, [data])),
            ),
          )
          as _i20.Future<_i17.Document>);

  @override
  _i18.Query where(
    String? field, {
    dynamic isEqualTo,
    dynamic isNotEqualTo,
    dynamic isGreaterThan,
    dynamic isGreaterThanOrEqualTo,
    dynamic isLessThan,
    dynamic isLessThanOrEqualTo,
    List<dynamic>? whereIn,
    dynamic contains,
    dynamic startsWith,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #where,
              [field],
              {
                #isEqualTo: isEqualTo,
                #isNotEqualTo: isNotEqualTo,
                #isGreaterThan: isGreaterThan,
                #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
                #isLessThan: isLessThan,
                #isLessThanOrEqualTo: isLessThanOrEqualTo,
                #whereIn: whereIn,
                #contains: contains,
                #startsWith: startsWith,
              },
            ),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(
                #where,
                [field],
                {
                  #isEqualTo: isEqualTo,
                  #isNotEqualTo: isNotEqualTo,
                  #isGreaterThan: isGreaterThan,
                  #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
                  #isLessThan: isLessThan,
                  #isLessThanOrEqualTo: isLessThanOrEqualTo,
                  #whereIn: whereIn,
                  #contains: contains,
                  #startsWith: startsWith,
                },
              ),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(
                #where,
                [field],
                {
                  #isEqualTo: isEqualTo,
                  #isNotEqualTo: isNotEqualTo,
                  #isGreaterThan: isGreaterThan,
                  #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
                  #isLessThan: isLessThan,
                  #isLessThanOrEqualTo: isLessThanOrEqualTo,
                  #whereIn: whereIn,
                  #contains: contains,
                  #startsWith: startsWith,
                },
              ),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query orderBy(String? field, {bool? descending = false}) =>
      (super.noSuchMethod(
            Invocation.method(#orderBy, [field], {#descending: descending}),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#orderBy, [field], {#descending: descending}),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#orderBy, [field], {#descending: descending}),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query limit(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#limit, [count]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#limit, [count]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#limit, [count]),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query offset(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#offset, [count]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#offset, [count]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#offset, [count]),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query startAfter(_i17.Document? document) =>
      (super.noSuchMethod(
            Invocation.method(#startAfter, [document]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#startAfter, [document]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#startAfter, [document]),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query startAfterId(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#startAfterId, [documentId]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#startAfterId, [documentId]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#startAfterId, [documentId]),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query select(List<String>? fields) =>
      (super.noSuchMethod(
            Invocation.method(#select, [fields]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#select, [fields]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#select, [fields]),
            ),
          )
          as _i18.Query);

  @override
  _i20.Future<_i17.QuerySnapshot> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i20.Future<_i17.QuerySnapshot>.value(
              _FakeQuerySnapshot_20(this, Invocation.method(#get, [])),
            ),
            returnValueForMissingStub: _i20.Future<_i17.QuerySnapshot>.value(
              _FakeQuerySnapshot_20(this, Invocation.method(#get, [])),
            ),
          )
          as _i20.Future<_i17.QuerySnapshot>);
}

/// A class which mocks [DocumentRef].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRef extends _i1.Mock implements _i13.DocumentRef {
  @override
  String get collection =>
      (super.noSuchMethod(
            Invocation.getter(#collection),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collection),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collection),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i19.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  _i16.SubcollectionRef subcollection(String? childCollection) =>
      (super.noSuchMethod(
            Invocation.method(#subcollection, [childCollection]),
            returnValue: _FakeSubcollectionRef_17(
              this,
              Invocation.method(#subcollection, [childCollection]),
            ),
            returnValueForMissingStub: _FakeSubcollectionRef_17(
              this,
              Invocation.method(#subcollection, [childCollection]),
            ),
          )
          as _i16.SubcollectionRef);

  @override
  _i20.Future<_i17.Document?> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i20.Future<_i17.Document?>.value(),
            returnValueForMissingStub: _i20.Future<_i17.Document?>.value(),
          )
          as _i20.Future<_i17.Document?>);

  @override
  _i20.Future<_i17.Document?> update(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#update, [data]),
            returnValue: _i20.Future<_i17.Document?>.value(),
            returnValueForMissingStub: _i20.Future<_i17.Document?>.value(),
          )
          as _i20.Future<_i17.Document?>);

  @override
  _i20.Future<_i17.Document?> set(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#set, [data]),
            returnValue: _i20.Future<_i17.Document?>.value(),
            returnValueForMissingStub: _i20.Future<_i17.Document?>.value(),
          )
          as _i20.Future<_i17.Document?>);

  @override
  _i20.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Stream<_i12.DocumentChange> snapshots() =>
      (super.noSuchMethod(
            Invocation.method(#snapshots, []),
            returnValue: _i20.Stream<_i12.DocumentChange>.empty(),
            returnValueForMissingStub: _i20.Stream<_i12.DocumentChange>.empty(),
          )
          as _i20.Stream<_i12.DocumentChange>);
}

/// A class which mocks [SubcollectionRef].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubcollectionRef extends _i1.Mock implements _i16.SubcollectionRef {
  @override
  String get parentCollection =>
      (super.noSuchMethod(
            Invocation.getter(#parentCollection),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#parentCollection),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#parentCollection),
            ),
          )
          as String);

  @override
  String get parentId =>
      (super.noSuchMethod(
            Invocation.getter(#parentId),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#parentId),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#parentId),
            ),
          )
          as String);

  @override
  String get childCollection =>
      (super.noSuchMethod(
            Invocation.getter(#childCollection),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#childCollection),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#childCollection),
            ),
          )
          as String);

  @override
  String get collectionPath =>
      (super.noSuchMethod(
            Invocation.getter(#collectionPath),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collectionPath),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collectionPath),
            ),
          )
          as String);

  @override
  _i15.OrignaBase get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeOrignaBase_15(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeOrignaBase_15(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i15.OrignaBase);

  @override
  String get collectionName =>
      (super.noSuchMethod(
            Invocation.getter(#collectionName),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
          )
          as String);

  @override
  _i13.DocumentRef doc(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [id]),
            returnValue: _FakeDocumentRef_16(
              this,
              Invocation.method(#doc, [id]),
            ),
            returnValueForMissingStub: _FakeDocumentRef_16(
              this,
              Invocation.method(#doc, [id]),
            ),
          )
          as _i13.DocumentRef);

  @override
  _i20.Future<_i17.Document> add(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#add, [data]),
            returnValue: _i20.Future<_i17.Document>.value(
              _FakeDocument_18(this, Invocation.method(#add, [data])),
            ),
            returnValueForMissingStub: _i20.Future<_i17.Document>.value(
              _FakeDocument_18(this, Invocation.method(#add, [data])),
            ),
          )
          as _i20.Future<_i17.Document>);

  @override
  _i20.Future<_i17.QuerySnapshot> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i20.Future<_i17.QuerySnapshot>.value(
              _FakeQuerySnapshot_20(this, Invocation.method(#get, [])),
            ),
            returnValueForMissingStub: _i20.Future<_i17.QuerySnapshot>.value(
              _FakeQuerySnapshot_20(this, Invocation.method(#get, [])),
            ),
          )
          as _i20.Future<_i17.QuerySnapshot>);

  @override
  _i16.SubcollectionRef subcollection(
    String? docId,
    String? nestedCollection,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subcollection, [docId, nestedCollection]),
            returnValue: _FakeSubcollectionRef_17(
              this,
              Invocation.method(#subcollection, [docId, nestedCollection]),
            ),
            returnValueForMissingStub: _FakeSubcollectionRef_17(
              this,
              Invocation.method(#subcollection, [docId, nestedCollection]),
            ),
          )
          as _i16.SubcollectionRef);

  @override
  _i18.Query where(
    String? field, {
    dynamic isEqualTo,
    dynamic isNotEqualTo,
    dynamic isGreaterThan,
    dynamic isGreaterThanOrEqualTo,
    dynamic isLessThan,
    dynamic isLessThanOrEqualTo,
    List<dynamic>? whereIn,
    dynamic contains,
    dynamic startsWith,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #where,
              [field],
              {
                #isEqualTo: isEqualTo,
                #isNotEqualTo: isNotEqualTo,
                #isGreaterThan: isGreaterThan,
                #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
                #isLessThan: isLessThan,
                #isLessThanOrEqualTo: isLessThanOrEqualTo,
                #whereIn: whereIn,
                #contains: contains,
                #startsWith: startsWith,
              },
            ),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(
                #where,
                [field],
                {
                  #isEqualTo: isEqualTo,
                  #isNotEqualTo: isNotEqualTo,
                  #isGreaterThan: isGreaterThan,
                  #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
                  #isLessThan: isLessThan,
                  #isLessThanOrEqualTo: isLessThanOrEqualTo,
                  #whereIn: whereIn,
                  #contains: contains,
                  #startsWith: startsWith,
                },
              ),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(
                #where,
                [field],
                {
                  #isEqualTo: isEqualTo,
                  #isNotEqualTo: isNotEqualTo,
                  #isGreaterThan: isGreaterThan,
                  #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
                  #isLessThan: isLessThan,
                  #isLessThanOrEqualTo: isLessThanOrEqualTo,
                  #whereIn: whereIn,
                  #contains: contains,
                  #startsWith: startsWith,
                },
              ),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query orderBy(String? field, {bool? descending = false}) =>
      (super.noSuchMethod(
            Invocation.method(#orderBy, [field], {#descending: descending}),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#orderBy, [field], {#descending: descending}),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#orderBy, [field], {#descending: descending}),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query limit(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#limit, [count]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#limit, [count]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#limit, [count]),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query offset(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#offset, [count]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#offset, [count]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#offset, [count]),
            ),
          )
          as _i18.Query);

  @override
  _i20.Stream<_i12.DocumentChange> snapshots() =>
      (super.noSuchMethod(
            Invocation.method(#snapshots, []),
            returnValue: _i20.Stream<_i12.DocumentChange>.empty(),
            returnValueForMissingStub: _i20.Stream<_i12.DocumentChange>.empty(),
          )
          as _i20.Stream<_i12.DocumentChange>);

  @override
  _i18.Query startAfter(_i17.Document? document) =>
      (super.noSuchMethod(
            Invocation.method(#startAfter, [document]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#startAfter, [document]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#startAfter, [document]),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query startAfterId(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#startAfterId, [documentId]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#startAfterId, [documentId]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#startAfterId, [documentId]),
            ),
          )
          as _i18.Query);

  @override
  _i18.Query select(List<String>? fields) =>
      (super.noSuchMethod(
            Invocation.method(#select, [fields]),
            returnValue: _FakeQuery_19(
              this,
              Invocation.method(#select, [fields]),
            ),
            returnValueForMissingStub: _FakeQuery_19(
              this,
              Invocation.method(#select, [fields]),
            ),
          )
          as _i18.Query);
}

/// A class which mocks [Document].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocument extends _i1.Mock implements _i17.Document {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i19.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  String get collection =>
      (super.noSuchMethod(
            Invocation.getter(#collection),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collection),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#collection),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  bool get exists =>
      (super.noSuchMethod(
            Invocation.getter(#exists),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  T? get<T>(String? field) =>
      (super.noSuchMethod(
            Invocation.method(#get, [field]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  dynamic operator [](String? key) => super.noSuchMethod(
    Invocation.method(#[], [key]),
    returnValueForMissingStub: null,
  );

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
