// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/unit/seller_registration_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:orignabase/src/auth.dart' as _i3;
import 'package:orignabase/src/batch.dart' as _i14;
import 'package:orignabase/src/client.dart' as _i15;
import 'package:orignabase/src/collection.dart' as _i13;
import 'package:orignabase/src/config.dart' as _i6;
import 'package:orignabase/src/links.dart' as _i8;
import 'package:orignabase/src/metrics.dart' as _i10;
import 'package:orignabase/src/offline.dart' as _i5;
import 'package:orignabase/src/presence.dart' as _i7;
import 'package:orignabase/src/push.dart' as _i9;
import 'package:orignabase/src/realtime.dart' as _i12;
import 'package:orignabase/src/storage.dart' as _i4;
import 'package:orignabase/src/vector.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseAuth_1 extends _i1.SmartFake
    implements _i3.OrignaBaseAuth {
  _FakeOrignaBaseAuth_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseStorage_2 extends _i1.SmartFake
    implements _i4.OrignaBaseStorage {
  _FakeOrignaBaseStorage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfflineCache_3 extends _i1.SmartFake implements _i5.OfflineCache {
  _FakeOfflineCache_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseConfig_4 extends _i1.SmartFake
    implements _i6.OrignaBaseConfig {
  _FakeOrignaBaseConfig_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePresence_5 extends _i1.SmartFake
    implements _i7.OrignaBasePresence {
  _FakeOrignaBasePresence_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseLinks_6 extends _i1.SmartFake
    implements _i8.OrignaBaseLinks {
  _FakeOrignaBaseLinks_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBasePush_7 extends _i1.SmartFake
    implements _i9.OrignaBasePush {
  _FakeOrignaBasePush_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrignaBaseMetrics_8 extends _i1.SmartFake
    implements _i10.OrignaBaseMetrics {
  _FakeOrignaBaseMetrics_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVectorSearch_9 extends _i1.SmartFake implements _i11.VectorSearch {
  _FakeVectorSearch_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_10 extends _i1.SmartFake
    implements _i12.RealtimeClient {
  _FakeRealtimeClient_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionRef_11 extends _i1.SmartFake
    implements _i13.CollectionRef {
  _FakeCollectionRef_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_12 extends _i1.SmartFake implements _i14.WriteBatch {
  _FakeWriteBatch_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrignaBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrignaBase extends _i1.Mock implements _i15.OrignaBase {
  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i16.dummyValue<String>(this, Invocation.getter(#url)),
            returnValueForMissingStub: _i16.dummyValue<String>(
              this,
              Invocation.getter(#url),
            ),
          )
          as String);

  @override
  _i2.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_0(this, Invocation.getter(#httpClient)),
            returnValueForMissingStub: _FakeClient_0(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i2.Client);

  @override
  _i3.OrignaBaseAuth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeOrignaBaseAuth_1(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeOrignaBaseAuth_1(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i3.OrignaBaseAuth);

  @override
  _i4.OrignaBaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeOrignaBaseStorage_2(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeOrignaBaseStorage_2(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i4.OrignaBaseStorage);

  @override
  _i5.OfflineCache get offline =>
      (super.noSuchMethod(
            Invocation.getter(#offline),
            returnValue: _FakeOfflineCache_3(this, Invocation.getter(#offline)),
            returnValueForMissingStub: _FakeOfflineCache_3(
              this,
              Invocation.getter(#offline),
            ),
          )
          as _i5.OfflineCache);

  @override
  _i6.OrignaBaseConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeOrignaBaseConfig_4(
              this,
              Invocation.getter(#config),
            ),
            returnValueForMissingStub: _FakeOrignaBaseConfig_4(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i6.OrignaBaseConfig);

  @override
  _i7.OrignaBasePresence get presence =>
      (super.noSuchMethod(
            Invocation.getter(#presence),
            returnValue: _FakeOrignaBasePresence_5(
              this,
              Invocation.getter(#presence),
            ),
            returnValueForMissingStub: _FakeOrignaBasePresence_5(
              this,
              Invocation.getter(#presence),
            ),
          )
          as _i7.OrignaBasePresence);

  @override
  _i8.OrignaBaseLinks get links =>
      (super.noSuchMethod(
            Invocation.getter(#links),
            returnValue: _FakeOrignaBaseLinks_6(
              this,
              Invocation.getter(#links),
            ),
            returnValueForMissingStub: _FakeOrignaBaseLinks_6(
              this,
              Invocation.getter(#links),
            ),
          )
          as _i8.OrignaBaseLinks);

  @override
  _i9.OrignaBasePush get push =>
      (super.noSuchMethod(
            Invocation.getter(#push),
            returnValue: _FakeOrignaBasePush_7(this, Invocation.getter(#push)),
            returnValueForMissingStub: _FakeOrignaBasePush_7(
              this,
              Invocation.getter(#push),
            ),
          )
          as _i9.OrignaBasePush);

  @override
  _i10.OrignaBaseMetrics get metrics =>
      (super.noSuchMethod(
            Invocation.getter(#metrics),
            returnValue: _FakeOrignaBaseMetrics_8(
              this,
              Invocation.getter(#metrics),
            ),
            returnValueForMissingStub: _FakeOrignaBaseMetrics_8(
              this,
              Invocation.getter(#metrics),
            ),
          )
          as _i10.OrignaBaseMetrics);

  @override
  _i11.VectorSearch get vectorSearch =>
      (super.noSuchMethod(
            Invocation.getter(#vectorSearch),
            returnValue: _FakeVectorSearch_9(
              this,
              Invocation.getter(#vectorSearch),
            ),
            returnValueForMissingStub: _FakeVectorSearch_9(
              this,
              Invocation.getter(#vectorSearch),
            ),
          )
          as _i11.VectorSearch);

  @override
  _i12.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_10(
              this,
              Invocation.getter(#realtime),
            ),
            returnValueForMissingStub: _FakeRealtimeClient_10(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i12.RealtimeClient);

  @override
  set auth(_i3.OrignaBaseAuth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i4.OrignaBaseStorage? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set offline(_i5.OfflineCache? value) => super.noSuchMethod(
    Invocation.setter(#offline, value),
    returnValueForMissingStub: null,
  );

  @override
  set config(_i6.OrignaBaseConfig? value) => super.noSuchMethod(
    Invocation.setter(#config, value),
    returnValueForMissingStub: null,
  );

  @override
  set presence(_i7.OrignaBasePresence? value) => super.noSuchMethod(
    Invocation.setter(#presence, value),
    returnValueForMissingStub: null,
  );

  @override
  set links(_i8.OrignaBaseLinks? value) => super.noSuchMethod(
    Invocation.setter(#links, value),
    returnValueForMissingStub: null,
  );

  @override
  set push(_i9.OrignaBasePush? value) => super.noSuchMethod(
    Invocation.setter(#push, value),
    returnValueForMissingStub: null,
  );

  @override
  set metrics(_i10.OrignaBaseMetrics? value) => super.noSuchMethod(
    Invocation.setter(#metrics, value),
    returnValueForMissingStub: null,
  );

  @override
  set vectorSearch(_i11.VectorSearch? value) => super.noSuchMethod(
    Invocation.setter(#vectorSearch, value),
    returnValueForMissingStub: null,
  );

  @override
  _i13.CollectionRef collection(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [name]),
            returnValue: _FakeCollectionRef_11(
              this,
              Invocation.method(#collection, [name]),
            ),
            returnValueForMissingStub: _FakeCollectionRef_11(
              this,
              Invocation.method(#collection, [name]),
            ),
          )
          as _i13.CollectionRef);

  @override
  _i14.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_12(
              this,
              Invocation.method(#batch, []),
            ),
            returnValueForMissingStub: _FakeWriteBatch_12(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i14.WriteBatch);

  @override
  _i17.Future<Map<String, dynamic>> graphql(
    String? query, {
    Map<String, dynamic>? variables,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#graphql, [query], {#variables: variables}),
            returnValue: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i17.Future<Map<String, dynamic>>);

  @override
  _i17.Future<Map<String, dynamic>> request(
    String? method,
    String? path, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [method, path],
              {#body: body, #headers: headers},
            ),
            returnValue: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i17.Future<Map<String, dynamic>>);

  @override
  _i17.Future<Map<String, dynamic>> search(
    String? index,
    String? query, {
    int? limit,
    int? offset,
    String? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [index, query],
              {#limit: limit, #offset: offset, #filter: filter},
            ),
            returnValue: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i17.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i17.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
